version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: build
      include: scope
    reviewers:
      - "oscal-compass/compliance-trestle-maintainers"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: build
      include: scope
    reviewers:
      - "oscal-compass/compliance-trestle-maintainers"
    open-pull-requests-limit: 10
