header:
  schema-version: 2.0.0
  last-updated: '2025-03-20'
  last-reviewed: '2025-03-20'
  url: https://github.com/oscal-compass/compliance-trestle/blob/develop/.github/security-insights.yml
  project-si-source: https://raw.githubusercontent.com/oscal-compass/.github/refs/heads/main/.github/security-insights.yml
  comment: |
    This file contains only the repository information for the Trestle project.

repository:
  url: https://github.com/oscal-compass/compliance-trestle
  status: active
  bug-fixes-only: false
  accepts-change-request: true
  accepts-automated-change-request: true
  no-third-party-packages: false
  # From the complaince-trestle MAINTAINER.md file
  # https://github.com/oscal-compass/compliance-trestle/blob/develop/MAINTAINERS.md
  core-team:
  - name:        Alejandro Jose Leiva Palomo
    primary:     true
  - name:        Christopher Butler
    primary:     true
  - name:        Lou Degenaro
    primary:     true
  - name:        Jennifer Power
    primary:     true
  - name:        Manjiree Gadgil
    primary:     true
  - name:        Vikas Agarwal
    primary:     true
  documentation:
    contributing-guide: https://github.com/oscal-compass/compliance-trestle/blob/develop/CONTRIBUTING.md
    security-policy: https://github.com/oscal-compass/community/blob/main/SECURITY.md
  license:
    url: https://github.com/oscal-compass/compliance-trestle/blob/develop/LICENSE
    expression: Apache-2.0
  release:
    changelog: https://github.com/oscal-compass/compliance-trestle/blob/develop/CHANGELOG.md
    automated-pipeline: true
    attestations:
      - name: PyPI Publish Attestation
        location: https://pypi.org/project/compliance-trestle/#compliance_trestle-{version}.tar.gz
        predicate-uri: https://docs.pypi.org/attestations/publish/v1
        comment: |
          This attestation communicates the Trusted Publisher identity
          used to publish the project.
    distribution-points:
      - uri: https://github.com/oscal-compass/compliance-trestle/releases
        comment: GitHub Release Page
      - uri: https://pypi.org/project/compliance-trestle/
  security:
    assessments:
      self:
        comment: |
          Self assessment has not yet been completed.
