sonar.organization=compliance-trestle
sonar.projectKey=compliance-trestle

sonar.sources=trestle
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=release-schemas/**,docs/**,images/**,internal_spec_documents/**,nist-content/**,trestle/oscal/**
sonar.coverage.exclusions=**/tmp/pytest-of-*/**,**/.pytest_cache/**

# SCM settings
sonar.scm.disabled=false
sonar.scm.provider=git