# -*- mode:python; coding:utf-8 -*-

# Copyright (c) 2020 IBM Corp. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
r"""
Script to normalize oscal after significant changes with version 1.0.0.

It then reorders the classes so there are minimal forwards required.
This script is normally called by gen_oscal.py when models are generated.

gen_oscal.py only need to be run when there is a need to update the python oscal classes to track new schemas
in the https://github.com/usnistgov/OSCAL/releases web site.  The local version is created manually by:
- download the zip/tar for the desired version
- extract the contents
- copy the json/schema/*.json files into the release-schemas folder

The main purpose of this script is to collapse the long-name versions of the classes into as simple a version as
possible, while also collecting common classes into a separate file, common.py.

The second purpose is to remove all the __root__ classes from common.py.  __root__ classes are classes that wrap a
single __root__ member in the class along with its type - which could be a simple string, integer, or complex regex.
If the __root__ classes are not removed, simple string assignment would look like:

param.values[0] = ParameterValue(__root__='foo')

instead of:

param.values[0] = 'foo'

The removal of __root__ is performed by extracting the type (and its possible regex) and substituting it in classes
that reference the __root__ class.  For example:

class StringDatatype(OscalBaseModel):
    __root__: constr(regex=r'^\S(.*\S)?$')

class Parameter(OscalBaseModel):
    values: Optional[List[StringDataType]] = Field(None)

In this case Parameter values reference a root class that is a constr type with regex, so we substitute the regex as:

class Parameter(OscalBaseModel):
    values: Optional[List[constr(regex=r'^\S(.*\S)?$')]] = Field(None)

This has no impact on internal validation of the values and performs identically without the need to wrap strings
in a StringDatatype with __root__ value specified.

For convenience the original root classes are left in common.py for reference, but the root classes should never
be referenced by name.

The only exception to this is OscalVersion, which has a special validator inserted by this script.

Note that __root__ classes in the other oscal .py files are left as-is since they don't tend to be referenced much
if at all in the trestle code - but they could also be removed by extensions to this script.

NOTE: The routine is fully automatic except the new Mapping class requires a slight manual edit to MappingCollection.

"""

import logging
import pathlib
import re

logger = logging.getLogger(__name__)


def get_oscal_version_regex():
    """Read OSCAL_VERSION_REGEX from the generated __init__.py file.

    This reads from file rather than importing to avoid module caching issues
    during generation when the file is being modified.
    """
    with open('trestle/oscal/__init__.py', 'r') as f:
        for line in f:
            if line.startswith('OSCAL_VERSION_REGEX'):
                match = re.search(r"= (r'[^']+')", line)
                if match:
                    return match.group(1)
    raise RuntimeError('OSCAL_VERSION_REGEX not found in trestle/oscal/__init__.py')


OSCAL_VERSION_REGEX = get_oscal_version_regex()
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())

class_header = 'class '

# List of filestems not including 'complete' or 'common'
# 'common' is generated by this script.  'complete.py' comes from NIST and is ignored
# mapping does not exist in the schema until new oscal is released at which point it should be added here
fstems = ['assessment_plan', 'assessment_results', 'catalog', 'component', 'poam', 'profile', 'ssp', 'mapping']

alias_map = {
    'assessment_plan': 'assessment-plan',
    'assessment_results': 'assessment-results',
    'catalog': 'catalog',
    'component': 'component-definition',
    'mapping': 'mapping-collection',
    'poam': 'plan-of-action-and-milestones',
    'profile': 'profile',
    'ssp': 'system-security-plan',
}

camel_map = {
    'assessment_plan': 'AssessmentPlan',
    'assessment_results': 'AssessmentResults',
    'catalog': 'Catalog',
    'component': 'ComponentDefinition',
    'mapping': 'MappingCollection',
    'poam': 'PlanOfActionAndMilestones',
    'profile': 'Profile',
    'ssp': 'SystemSecurityPlan',
}

prefix_map = {
    'assessment_plan': 'Ap',
    'assessment_results': 'Ar',
    'catalog': 'Cat',
    'component': 'Comp',
    'mapping': 'Map',
    'poam': 'Poam',
    'profile': 'Prof',
    'ssp': 'Ssp',
}

# these prefixes are stripped repeatedly from class names until no more changes
prefixes_to_strip = [
    'OscalMetadata',
    'OscalAssessmentCommon',
    'OscalImplementationCommon',
    'OscalComponentDefinition',
    'OscalCatalog',
    'OscalControl',
    'OscalMapping',
    'OscalSsp',
    'OscalPoam',
    'OscalProfile',
    'OscalAr',
    'OscalAp',
    'Common',
]

license_header = (
    '# -*- mode:python; coding:utf-8 -*-\n'
    '# Copyright (c) 2020 IBM Corp. All rights reserved.\n'
    '#\n'
    '# Licensed under the Apache License, Version 2.0 (the "License");\n'
    '# you may not use this file except in compliance with the License.\n'
    '# You may obtain a copy of the License at\n'
    '#\n'
    '#     https://www.apache.org/licenses/LICENSE-2.0\n'
    '#\n'
    '# Unless required by applicable law or agreed to in writing, software\n'
    '# distributed under the License is distributed on an "AS IS" BASIS,\n'
    '# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n'
    '# See the License for the specific language governing permissions and\n'
    '# limitations under the License.\n'
)

main_header = """
#
#
####### DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT ######
#                                                                        #
#        This file is automatically generated by gen_oscal.py            #
#                                                                        #
####### DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT ######
#
#
from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, EmailStr, Extra, Field, conint, constr, validator

from trestle.core.base_model import OscalBaseModel
from trestle.oscal import OSCAL_VERSION_REGEX, OSCAL_VERSION
"""

oscal_validator_code = """

    @validator('__root__')
    def oscal_version_is_valid(cls, v):
        strict_version = False
        if not strict_version:
            return v
        p = re.compile(OSCAL_VERSION_REGEX)
        matched = p.match(v)
        if matched is None:
            raise ValueError(f'OSCAL version: {v} is not supported, use {OSCAL_VERSION} instead.')
        return v

"""


def add_union_validators(class_name, discriminator_field, other_variant):
    """
    Generate smart Union validator code for OSCAL 1.2.0 Union types.

    Args:
        class_name: Name of the current class (e.g., 'Group1', 'Parameter1')
        discriminator_field: Field that indicates this variant (e.g., 'groups', 'values')
        other_variant: Name of the other Union variant (e.g., 'Group2', 'Parameter2')

    Returns:
        String containing the validator code to add to the class
    """
    other_discriminator = {'groups': 'controls', 'controls': 'groups', 'values': 'select', 'select': 'values'}.get(
        discriminator_field, ''
    )

    return f'''
    @classmethod
    def __get_validators__(cls):
        yield cls._smart_union_validator

    @classmethod
    def _smart_union_validator(cls, v):
        """Smart validator that chooses {class_name} if data has {discriminator_field}, otherwise tries {other_variant}."""
        if isinstance(v, dict):
            # If dict has '{discriminator_field}' field, use {class_name}
            if '{discriminator_field}' in v:
                return cls.parse_obj(v)
            # If dict has '{other_discriminator}' field, use {other_variant}
            elif '{other_discriminator}' in v:
                return {other_variant}.parse_obj(v)
        # For non-dict or ambiguous cases, try {class_name} first (this class)
        try:
            return cls.parse_obj(v) if isinstance(v, dict) else v
        except Exception:
            # If {class_name} fails, try {other_variant}
            return {other_variant}.parse_obj(v) if isinstance(v, dict) else v


'''


class RelOrder:
    """Capture relative location of each class in list to its refs and deps."""

    def __init__(self, max_index):
        """Initialize with size of list being reordered."""
        self.latest_dep = 0
        self.earliest_ref = max_index


class ClassText:
    """Hold class text as named blocks with references to the added classes and capture its refs."""

    def __init__(self, first_line, parent_name):
        """Construct with first line of class definition and store the parent file name."""
        self.lines = [first_line.rstrip()]
        n = first_line.find('(')
        self.name = first_line[len(class_header) : n]
        self.parent_names = [parent_name]
        self.original_name = self.name
        self.original_names = [self.name]  # Track all original names when classes are merged
        self.unique_name = None
        self.refs = set()
        self.full_refs = set()
        self.found_all_links = False
        self.is_self_ref = False
        self.is_local = False
        self.body_text = None

    def add_line(self, line):
        """Add new line to class text."""
        self.lines.append(line)

    def add_ref_if_good(self, ref_name):
        """Add non-empty refs that are not in common."""
        if ref_name and 'common.' not in ref_name:
            self.refs.add(ref_name)

    def add_ref_pattern(self, p, line):
        """Add refs for new class names found based on pattern."""
        new_refs = p.findall(line)
        if new_refs:
            for r in new_refs:
                if isinstance(r, tuple):
                    for s in r:
                        self.add_ref_if_good(s)
                else:
                    self.add_ref_if_good(r)

    @staticmethod
    def find_index(class_text_list, name):
        """Find index of class in list by name."""
        nclasses = len(class_text_list)
        for i in range(nclasses):
            if class_text_list[i].name == name:
                return i
        return -1

    def generate_body_text(self):
        """Get body text with whitespace removed."""
        # The body starts after the first colon
        full_text = ''
        for line in self.lines:
            # this adds the line with whitespace removed
            full_text += ''.join(line.split(' '))
        colon = full_text.find(':')
        self.body_text = full_text[colon:]

    @staticmethod
    def generate_all_body_text(classes):
        """Get the body of all classes into text."""
        new_classes = []
        for c in classes:
            c.generate_body_text()
            new_classes.append(c)
        return new_classes

    def bodies_equal(self, other):
        """Are class bodies equal with whitespace ignored."""
        return self.body_text == other.body_text

    def add_all_refs(self, line):
        """Find all refd class names found in line and add to references."""
        # find lone strings with no brackets
        p = re.compile(r'.*\:\s*([^\s\[\]]+).*')
        self.add_ref_pattern(p, line)
        # find objects in one or more bracket sets with possible first token and comma
        p = re.compile(r'.*\[(?:(.*),\s*)?((?:\[??[^\[]*?))\]')
        self.add_ref_pattern(p, line)
        # add refs found in optional unions
        p = re.compile(r'.*Optional\[Union\[([^,]+)')
        self.add_ref_pattern(p, line)
        # add refs found in pipe-style unions (Python 3.10+ syntax: Type1 | Type2 | Type3)
        # Match type names after | that are followed by |, =, ], comma, or space before =
        p = re.compile(r'\|\s*(\w+)(?:\s*(?:\||=|\]|,))')
        self.add_ref_pattern(p, line)
        # add refs found for "Algorithm"
        if ' Algorithm ' in line:
            self.add_ref_if_good('Algorithm')
        # add refs found for "IdentifierType"
        if ' IdentifierType ' in line:
            self.add_ref_if_good('IdentifierType')
        return line

    def find_direct_refs(self, class_names_list):
        """Find direct refs without recursion."""
        for ref in self.refs:
            if ref == self.name:
                self.is_self_ref = True
            if ref in class_names_list and not ref == self.name:
                self.full_refs.add(ref)
            else:
                # Check if ref has a prefix (Cat_, Prof_) that needs to be stripped
                # This handles cases where refs are detected before prefix stripping
                for prefix in ['Cat_', 'Prof_']:
                    if ref.startswith(prefix):
                        stripped_ref = ref[len(prefix) :]
                        if stripped_ref in class_names_list and not stripped_ref == self.name:
                            self.full_refs.add(stripped_ref)
                            break
        if len(self.full_refs) == 0:
            self.found_all_links = True

    def find_order(self, class_text_list):
        """Find latest dep and earliest reference."""
        ro = RelOrder(len(class_text_list) - 1)
        # find first class that needs this class
        for i, ct in enumerate(class_text_list):
            if self.name in ct.full_refs:
                ro.earliest_ref = i
                break
        # find last class this one needs
        # make sure result is deterministic and does not depend on order from set
        sorted_ref_list = sorted(self.full_refs)
        for ref in sorted_ref_list:
            n = ClassText.find_index(class_text_list, ref)
            if n > ro.latest_dep:
                ro.latest_dep = n
        return ro

    def strip_prefix(self, prefix):
        """Strip the prefix from the class name only."""
        if self.name.startswith(prefix) and self.name != prefix:
            self.name = self.name.replace(prefix, '', 1)
            return True
        return False


def find_forward_refs(class_list, orders):
    """Find forward references within the file."""
    forward_names = set()
    for c in class_list:
        if c.is_self_ref:
            forward_names.add(c.name)
    for i in range(len(orders)):
        # If a class references something defined after it (i < latest_dep),
        # it needs update_forward_refs() to resolve the forward reference
        if i < orders[i].latest_dep:
            forward_names.add(class_list[i].name)

    forward_refs = []
    for c in class_list:
        if c.name in forward_names:
            # Skip Enums - they don't have update_forward_refs()
            if '(Enum)' not in c.lines[0]:
                forward_refs.append(f'{c.name}.update_forward_refs()')
    return forward_refs


def reorder(fstem, class_list):
    """Reorder the class list based on the location of its refs and deps."""
    # build list of all class names defined in file
    all_class_names = []
    for c in class_list:
        all_class_names.append(c.name)

    dups = {x for x in all_class_names if all_class_names.count(x) > 1}
    if len(dups) > 0:
        logger.error(f'ERROR Duplicate classes in {fstem}: {" ".join(dups)}')

    # find direct references for each class in list
    for n, c in enumerate(class_list):
        c.find_direct_refs(all_class_names)
        class_list[n] = c
        # Debug: trace key class references

    # Pre-sort: Move all classes with no dependencies to the front
    # This handles simple cases like URIDatatype that are referenced by many classes
    # but have no dependencies themselves
    leaf_classes = []
    non_leaf_classes = []
    for c in class_list:
        if len(c.full_refs) == 0:
            leaf_classes.append(c)
        else:
            non_leaf_classes.append(c)

    # Rebuild class_list with leaf classes first
    class_list = leaf_classes + non_leaf_classes

    # with full dependency info, now reorder the classes to remove forward refs
    did_swap = True
    loop_num = 0
    orders = None
    max_iterations = 5000  # Increased from 1000 to handle complex dependencies
    out_of_order_count = 0
    last_out_of_order_count = -1
    stuck_count = 0  # Count how many iterations we've been stuck

    while did_swap and loop_num < max_iterations:
        did_swap = False
        orders = []
        out_of_order_count = 0

        # find the relative placement of each class in list to its references and dependencies
        for c in class_list:
            ro = c.find_order(class_list)
            orders.append(ro)
            # Debug: trace key classes ordering

        # Count how many classes are out of order
        for i, ro in enumerate(orders):
            if not (ro.latest_dep <= i <= ro.earliest_ref):
                out_of_order_count += 1

        # Check if we're stuck and identify the problematic classes
        if out_of_order_count == last_out_of_order_count and out_of_order_count > 0:
            stuck_count += 1
            # If stuck for 100 iterations, give up - likely circular dependencies
            if stuck_count >= 100:
                break
        else:
            stuck_count = 0

        # Debug: trace progress every 100 iterations

        last_out_of_order_count = out_of_order_count

        # find first class that is before its dependencies (out of order) and move it after them
        for i, ro in enumerate(orders):
            # A class is correctly placed if it's after all its dependencies and before all its references
            if ro.latest_dep <= i <= ro.earliest_ref:
                continue
            # Class is out of order - need to move it
            ct = class_list[i]
            if i < ro.latest_dep:
                # Class is BEFORE its dependencies - move it AFTER them
                class_list.pop(i)
                # Insert after the latest dependency
                class_list.insert(ro.latest_dep, ct)
                # Debug: trace specific moves
                did_swap = True
                break
            elif i > ro.earliest_ref:
                # Class is AFTER its first reference - move it BEFORE that reference
                class_list.pop(i)
                class_list.insert(ro.earliest_ref, ct)
                # Debug: trace specific moves
                did_swap = True
                break
        loop_num += 1
    if did_swap:
        logger.warning('Excess iteration in reordering!')

    forward_refs = find_forward_refs(class_list, orders)

    # return reordered list of classes with no forward refs
    return class_list, forward_refs


def constrain_oscal_version(class_list):
    """Constrain allowed oscal version."""
    for j in range(len(class_list)):
        cls = class_list[j]
        for i in range(len(cls.lines)):
            line = cls.lines[i]
            nstart = line.find('oscal_version:')
            if nstart >= 0:
                nstr = line.find('str')
                if nstr >= 0:
                    cls.lines[i] = line.replace('str', f'constr(regex={OSCAL_VERSION_REGEX})')
                    class_list[j] = cls
    return class_list


def load_classes(fstem):
    """Load all classes from a python file."""
    all_classes = []
    header = []
    forward_refs = []

    class_text = None
    done_header = False

    fname = pathlib.Path('trestle/oscal/tmp') / (fstem + '.py')

    with open(fname, 'r', encoding='utf8') as infile:
        for r in infile.readlines():
            # collect forward references
            if r.find('.update_forward_refs()') >= 0:
                forward_refs.append(r)
            elif r.find(class_header) == 0:  # start of new class
                done_header = True
                if class_text is not None:  # we are done with current class so add it
                    all_classes.append(class_text)
                class_text = ClassText(r, fstem)
            else:
                if not done_header:  # still in header
                    header.append(r.rstrip())
                else:
                    # this may not be needed
                    p = re.compile(r'.*Optional\[Union\[([^,]+),.*List\[Any\]')
                    refs = p.findall(r)
                    if len(refs) == 1:
                        logger.info(f'Replaced Any with {refs[0]} in {fstem}')
                        r_orig = r
                        r = r.replace('List[Any]', f'List[{refs[0]}]')
                        logger.info(f'{r_orig} -> {r}')
                    class_text.add_line(r.rstrip())

    all_classes.append(class_text)  # don't forget final class

    # force all oscal versions to the current one
    all_classes = constrain_oscal_version(all_classes)
    return all_classes


def load_all_classes():
    """Load all classes from all files on per file basis."""
    all_classes = []
    for fstem in fstems:
        all_classes.extend(load_classes(fstem))
    return all_classes


def keep_distinct(a, b):
    """If class names don't resolve to the same value then keep separate."""
    # It is possible two classes with very different names have the same bodies
    # This is allowed if the names are different enough since they provide useful context
    stripped_classes = strip_prefixes([a, b])
    a = stripped_classes[0]
    b = stripped_classes[1]
    if a.name == b.name:
        return False
    return True


def find_unique_classes(all_classes):
    """Find unique classes based mainly on bodies."""
    unique_classes = []
    all_classes = ClassText.generate_all_body_text(all_classes)
    for a in all_classes:
        # ignore the Model class - it is added at end
        if a.name == 'Model':
            continue
        is_unique = True
        for i, u in enumerate(unique_classes):
            if a.bodies_equal(u):
                if keep_distinct(a, u):
                    continue
                is_unique = False
                unique_classes[i].parent_names.append(a.parent_names[0])
                # Preserve all original names when merging classes
                unique_classes[i].original_names.append(a.original_name)
                break
        if is_unique:
            a.unique_name = a.original_name
            unique_classes.append(a)
    return unique_classes


def strip_prefixes(classes):
    """Strip prefixes from class names."""
    new_classes = []
    # are we stripping all names in a file
    full_file = len(classes) > 2
    all_names = [c.name for c in classes]
    for c in classes:
        made_change = True
        # keep stripping til clean
        while made_change:
            made_change = False
            for prefix in prefixes_to_strip:
                if c.strip_prefix(prefix):
                    # if we generated a collision with existing name, append integer
                    if full_file and c.name in all_names:
                        ii = 1
                        while f'c.name{ii}' in all_names:
                            ii += 1
                        c.name = f'{c.name}{ii}'
                    made_change = True
        new_classes.append(c)
    return new_classes


def fix_clashes(classes):
    """Fix clashes in names."""
    # If two classes have the same name and different bodies, adjust each name
    # Leave bodies alone
    # each new class name will be local to its one parent file
    nclasses = len(classes)
    changes = []
    for i in range(nclasses):
        for j in range(i + 1, nclasses):
            if classes[i].name == classes[j].name:
                a = classes[i]
                b = classes[j]
                if a.bodies_equal(b):
                    continue
                a_parents = a.parent_names
                b_parents = b.parent_names
                for a_parent in a_parents:
                    for b_parent in b_parents:
                        a_pre = prefix_map[a_parent]
                        a_new = a.name if a.name.startswith(a_pre) else a_pre + '_' + a.name
                        b_pre = prefix_map[b_parent]
                        b_new = b.name if b.name.startswith(b_pre) else b_pre + '_' + b.name
                        changes.append((a_parent, a.name, a_new))
                        changes.append((b_parent, b.name, b_new))

    # now make the actual class name changes
    new_classes = []
    for c in classes:
        for change in changes:
            for parent_name in c.parent_names:
                # find the one class with parent that matches the change - and change only its name
                if parent_name == change[0] and c.name == change[1]:
                    c.name = change[2]
                    # mark the class as local to the one file
                    c.is_local = True
                    break
        new_classes.append(c)
    return new_classes


def token_in_line(line, token):
    """Find if token is present in string."""
    # the second regex needs to include digits for Base64 vs. Base, Type vs. Type1 etc.
    pattern = r'(^|[^a-zA-Z_]+)' + token + r'($|[^a-zA-Z0-9_]+)'
    p = re.compile(pattern)
    hits = p.findall(line)
    return len(hits) > 0


def replace_token(line, str1, str2):
    """Replace token str1 with new str2 in line."""
    # pull out what you want to keep on left and right
    # rather than capture what you want and replace it
    if str1 not in line:
        return line
    # Use word boundary pattern to match the token
    # Match str1 when it's preceded by non-word char (or start) and followed by non-word char (or end)
    pattern = r'(?<![a-zA-Z0-9_])' + re.escape(str1) + r'(?![a-zA-Z0-9_])'
    line = re.sub(pattern, str2, line)
    return line


def is_common(cls):
    """Class is not common if _ in name or only one parent."""
    if '_' in cls.name:
        return False
    if len(cls.parent_names) == 1:
        return False
    return True


def _list_to_file_classes(classes):
    file_classes = {}
    for stem in fstems:
        file_classes[stem] = []
    file_classes['common'] = []

    for c in classes:
        file_classes[c.parent_names[0]].append(c)
    return file_classes


def _file_classes_to_list(file_classes, exclude_common):
    classes = []
    for item in file_classes.items():
        if item[0] == 'common' and exclude_common:
            continue
        for c in item[1]:
            classes.append(c)
    return classes


def refine_split(file_classes):
    """Make sure no references in common link to the other files."""
    # get list of original names in current common file
    common_names = []
    for c in file_classes['common']:
        common_names.append(c.unique_name)

    # find all original names of classes in other files that shouldn't be refd by common
    names = set()
    for stem in fstems:
        for c in file_classes[stem]:
            if (c.is_local) or (c.unique_name not in common_names):
                names.add(c.unique_name)
    names = list(names)

    # if any common class references outside common - exclude it from common
    not_com = []
    for c in file_classes['common']:
        # Force Group1 out of common - it references Group2 which is file-specific
        if c.name == 'Group1':
            not_com.append(c.name)
            continue
        excluded = False
        for line in c.lines:
            if excluded:
                break
            if '"' not in line and "'" not in line:
                for name in names:
                    if token_in_line(line, name):
                        not_com.append(c.name)
                        excluded = True
                        break

    # remove all not_com from com and add to other files as needed by parents
    new_com = []
    for c in file_classes['common']:
        if c.name in not_com:
            for parent in c.parent_names:
                file_classes[parent].append(c)
        else:
            new_com.append(c)
    file_classes['common'] = new_com
    return file_classes


def _find_in_classes(name, file_classes):
    # debugging utility
    found = []
    for item in file_classes.items():
        for c in item[1]:
            if name in c.name:
                found.append((item[0], c.name))
    return found


def _find_in_class_list(name, classes):
    # debugging utility
    found = []
    for c in classes:
        if name in c.name:
            found.append((name, c.name))
    return found


def split_classes(classes):
    """Split into separate common and other files."""
    file_classes = {}
    for stem in fstems:
        file_classes[stem] = []
    file_classes['common'] = []
    com_names = []

    for c in classes:
        if is_common(c):
            if c.name not in com_names:
                com_names.append(c.name)
                file_classes['common'].append(c)
        else:
            # remove clash prefix from the class name if present
            # the prefix is removed from bodies after the split
            c.name = c.name.split('_')[-1]
            for parent in c.parent_names:
                # the class carries with it that it is local and bound to the parent
                file_classes[parent].append(c)

    # keep removing classes in com that have external dependencies until it is clean
    new_ncom = 0
    while new_ncom != len(file_classes['common']):
        new_ncom = len(file_classes['common'])
        file_classes = refine_split(file_classes)
    return file_classes


def reorder_classes(fstem, classes):
    """Reorder the classes to minimize needed forwards."""
    classes = sorted(classes, key=lambda c: c.name)
    new_classes = []
    for c in classes:
        for line in c.lines:
            _ = c.add_all_refs(line)
        new_classes.append(c)
    reordered, forward_refs = reorder(fstem, new_classes)
    return reordered, forward_refs


def write_oscal(classes, forward_refs, fstem):
    """Write out oscal.py with all classes in it."""
    with open(f'trestle/oscal/{fstem}.py', 'w', encoding='utf8') as out_file:
        is_common = fstem == 'common'

        out_file.write(license_header)
        out_file.write('\n')
        out_file.write(main_header)

        if not is_common:
            out_file.write('import trestle.oscal.common as common\n')
        out_file.write('\n\n')

        # Track if we've seen both Parameter1 and Parameter2 for adding the alias
        seen_parameter1 = False
        seen_parameter2 = False
        # Track if we've seen both Parties and Parties1 for adding the alias
        seen_parties = False
        seen_parties1 = False
        # Track profile.py Union variants for creating aliases
        seen_merge1 = False
        seen_merge2 = False
        seen_merge3 = False
        seen_import1 = False
        seen_import2 = False
        seen_insertcontrols1 = False
        seen_insertcontrols2 = False
        seen_setparameters = False

        for c in classes:
            # Skip the broken Group Union wrapper in common.py that references Cat_Group2
            if is_common and c.name == 'Group' and '__root__' in '\n'.join(c.lines):
                continue

            # Skip Union wrapper classes with __root__ - we use Union aliases instead
            if '__root__' in '\n'.join(c.lines):
                # Skip Parameter wrapper in common.py
                if is_common and c.name == 'Parameter':
                    continue
                # Skip Group wrapper in common.py
                if is_common and c.name == 'Group':
                    continue
                # Skip Merge, Import, InsertControls wrappers in profile.py
                if fstem == 'profile' and c.name in ['Merge', 'Import', 'InsertControls']:
                    continue

            # Fix: Replace Group pipe unions
            lines_to_write = c.lines
            if fstem in ['common', 'catalog', 'profile']:
                prefix = 'Cat_' if fstem == 'catalog' else ('Prof_' if fstem == 'profile' else '')
                lines_to_write = []
                for line in c.lines:
                    # Replace Cat_Group2/Prof_Group2 with Group2
                    if prefix:
                        line = line.replace(f'{prefix}Group2', 'Group2')
                    # The Group Union wrapper (__root__: Group1|Group2) is removed by kill_roots()
                    # So we need to expand list[Group] references to list[Group1|Group2]
                    # This matches the OSCAL 1.2.0 schema where the groups field recursively
                    # references the Group anyOf definition (which can be either Group1 or Group2)
                    # Group1 is now in catalog.py and profile.py (not common.py)
                    if c.name == 'Group1' and 'list[Group]' in line:
                        line = line.replace('list[Group]', 'list[Group1|Group2]')
                    # Fix malformed Parameter pipe unions in profile.py
                    if fstem == 'profile':
                        line = line.replace('Parameter1|Parameter2Constraint', 'common.ParameterConstraint')
                        line = line.replace('Parameter1|Parameter2Guideline', 'common.ParameterGuideline')
                        line = line.replace('Parameter1|Parameter2Selection', 'common.ParameterSelection')
                    # Replace inline Parameter1|Parameter2 unions with common.Parameter alias
                    if 'Parameter1|Parameter2' in line:
                        line = line.replace('Parameter1|Parameter2', 'common.Parameter')
                    lines_to_write.append(line)

            out_file.writelines('\n'.join(lines_to_write) + '\n')

            # Add smart Union validators for Group1 and Group2 in catalog/profile
            if c.name == 'Group1' and fstem in ['catalog', 'profile']:
                out_file.write(add_union_validators('Group1', 'groups', 'Group2'))
            if c.name == 'Group2' and fstem in ['catalog', 'profile']:
                out_file.write(add_union_validators('Group2', 'controls', 'Group1'))

            # Add smart Union validators for Parameter1 and Parameter2 in common
            if c.name == 'Parameter1' and is_common:
                out_file.write(add_union_validators('Parameter1', 'values', 'Parameter2'))
            if c.name == 'Parameter2' and is_common:
                out_file.write(add_union_validators('Parameter2', 'select', 'Parameter1'))

            # add special validator for OscalVersion
            if c.name == 'OscalVersion':
                out_file.write(oscal_validator_code)
            # add alias HowMany
            if c.name == 'HowManyValidValues':
                out_file.write('HowMany = HowManyValidValues\n\n\n')
            # Track Parameter1 and Parameter2
            if c.name == 'Parameter1':
                seen_parameter1 = True
                # Add alias Parameter after both Parameter1 and Parameter2 have been emitted
                if seen_parameter2:
                    out_file.write('# Backward compatibility alias for OSCAL 1.2.0\n')
                    out_file.write('# Parameter split into Parameter1 (with values) and Parameter2 (with select)\n')
                    out_file.write('Parameter = Union[Parameter1, Parameter2]\n\n\n')
            if c.name == 'Parameter2':
                seen_parameter2 = True
                # Add alias Parameter after both Parameter1 and Parameter2 have been emitted
                if seen_parameter1:
                    out_file.write('# Backward compatibility alias for OSCAL 1.2.0\n')
                    out_file.write('# Parameter split into Parameter1 (with values) and Parameter2 (with select)\n')
                    out_file.write('Parameter = Union[Parameter1, Parameter2]\n\n\n')
            # Track Parties and Parties1
            if c.name == 'Parties':
                seen_parties = True
                # Add alias Party after both Parties and Parties1 have been emitted
                if seen_parties1:
                    out_file.write('# Backward compatibility alias for OSCAL 1.2.0\n')
                    out_file.write('# Party renamed to Parties (with variants Parties1 and Parties)\n')
                    out_file.write('Party = Union[Parties1, Parties]\n\n\n')
            if c.name == 'Parties1':
                seen_parties1 = True
                # Add alias Party after both Parties and Parties1 have been emitted
                if seen_parties:
                    out_file.write('# Backward compatibility alias for OSCAL 1.2.0\n')
                    out_file.write('# Party renamed to Parties (with variants Parties1 and Parties)\n')
                    out_file.write('Party = Union[Parties1, Parties]\n\n\n')
            # Track profile.py Union variants and add aliases after all variants are defined
            if fstem == 'profile':
                # Track SetParameters variants and update forward refs
                # TODO: Investigate why reordering doesn't place these classes in the right order
                if c.name == 'SetParameters':
                    seen_setparameters = True
                if c.name == 'SetParameters1':
                    # Update SetParameters forward references after both variants are defined
                    # They reference Parameter1|Parameter2Constraint and Parameter1|Parameter2Guideline
                    if seen_setparameters:
                        out_file.write(
                            '# Update SetParameters forward references for Parameter constraints/guidelines\n'
                        )
                        out_file.write('SetParameters.update_forward_refs()\n')
                        out_file.write('SetParameters1.update_forward_refs()\n\n\n')

                # Track Merge variants and add Union alias after all are defined
                if c.name == 'Merge1':
                    seen_merge1 = True
                    if seen_merge2 and seen_merge3:
                        out_file.write('# Union alias for Merge variants\n')
                        out_file.write('Merge = Union[Merge1, Merge2, Merge3]\n\n\n')
                if c.name == 'Merge2':
                    seen_merge2 = True
                    if seen_merge1 and seen_merge3:
                        out_file.write('# Union alias for Merge variants\n')
                        out_file.write('Merge = Union[Merge1, Merge2, Merge3]\n\n\n')
                if c.name == 'Merge3':
                    seen_merge3 = True
                    if seen_merge1 and seen_merge2:
                        out_file.write('# Union alias for Merge variants\n')
                        out_file.write('Merge = Union[Merge1, Merge2, Merge3]\n\n\n')

                # Track Import variants
                if c.name == 'Import1':
                    seen_import1 = True
                    # Add Import Union alias after both variants are defined
                    if seen_import2:
                        out_file.write('# Union alias for Import variants\n')
                        out_file.write('Import = Union[Import1, Import2]\n\n\n')
                if c.name == 'Import2':
                    seen_import2 = True
                    # Add Import Union alias after both variants are defined
                    if seen_import1:
                        out_file.write('# Union alias for Import variants\n')
                        out_file.write('Import = Union[Import1, Import2]\n\n\n')

                # Track InsertControls variants
                if c.name == 'InsertControls1':
                    seen_insertcontrols1 = True
                    # Add InsertControls Union alias after both variants are defined
                    if seen_insertcontrols2:
                        out_file.write('# Union alias for InsertControls variants\n')
                        out_file.write('InsertControls = Union[InsertControls1, InsertControls2]\n\n\n')
                if c.name == 'InsertControls2':
                    seen_insertcontrols2 = True
                    # Add InsertControls Union alias after both variants are defined
                    if seen_insertcontrols1:
                        out_file.write('# Union alias for InsertControls variants\n')
                        out_file.write('InsertControls = Union[InsertControls1, InsertControls2]\n\n\n')
            # Add backward compatibility alias for ControlSelections after ControlSelectionsAll
            if c.name == 'ControlSelectionsAll':
                out_file.write('# Backward compatibility alias\n')
                out_file.write('# DEPRECATED: Use ControlSelectionsAll instead\n')
                out_file.write('ControlSelection = ControlSelectionsAll\n\n\n')
            # Add backward compatibility alias for ControlObjectiveSelections after ControlObjectiveSelectionsAll
            if c.name == 'ControlObjectiveSelectionsAll':
                out_file.write('# Backward compatibility alias\n')
                out_file.write('# DEPRECATED: Use ControlObjectiveSelectionsAll instead\n')
                out_file.write('ControlObjectiveSelection = ControlObjectiveSelectionsAll\n\n\n')

        if not is_common:
            # Add backward compatibility alias for SetParameter in non-common modules
            # In OSCAL 1.2.0, SetParameter is only in common module
            if fstem in ['component', 'profile', 'ssp']:
                out_file.write('# Backward compatibility alias for OSCAL 1.2.0\n')
                out_file.write('# SetParameter is now only in common module\n')
                out_file.write('SetParameter = common.SetParameter\n\n\n')

            out_file.writelines('class Model(OscalBaseModel):\n')
            alias = alias_map[fstem]
            snake = alias.replace('-', '_')
            class_name = camel_map[fstem]
            if '-' in alias:
                out_file.writelines(f"    {snake}: {class_name} = Field(..., alias='{alias}')\n")
            else:
                out_file.writelines(f'    {snake}: {class_name}\n')

        if forward_refs:
            if not is_common:
                out_file.writelines('\n\n')
            # Filter out Group.update_forward_refs() from common.py since we removed the Group Union wrapper
            filtered_refs = forward_refs
            if is_common:
                filtered_refs = [ref for ref in forward_refs if not ref.startswith('Group.')]
            out_file.writelines('\n'.join(filtered_refs) + '\n')
        
        # Add backward compatibility aliases for Timing classes in common module
        if is_common:
            out_file.write('\n\n# Backward compatibility aliases for Timing classes\n')
            out_file.write('# Use TimingOnDate, TimingWithinDateRange, TimingAtFrequency instead\n')
            out_file.write('Timing = TimingOnDate\n')
            out_file.write('Timing1 = TimingWithinDateRange\n')
            out_file.write('Timing2 = TimingAtFrequency\n')


# The below "additions" items have moved from individual model class to common.
# For backward compatibility between 1.1.2 and 1.0.4, add back these classes
# from common into the individual models via the bkwd_compat_1_0_4 method below.

# The list of stems (dict keys) is also used by the pydantic_interface_v1 modification
# method below, and thus the empty contents for some.

additions = {
    'assessment_plan': [
        'from trestle.oscal.common import AssessmentSubject1',
        'from trestle.oscal.common import AssessmentSubject2',
        'from trestle.oscal.common import RelatedObservation',
        'from trestle.oscal.common import StringDatatype',
        'from trestle.oscal.common import SystemComponent',
        'from trestle.oscal.common import TaskValidValues',
        'from trestle.oscal.common import TokenDatatype',
    ],
    'assessment_results': [
        'from trestle.oscal.common import AssessmentAssets',
        'from trestle.oscal.common import Observation',
        'from trestle.oscal.common import RelatedObservation',
        'from trestle.oscal.common import StringDatatype',
        'from trestle.oscal.common import SystemComponent',
        'from trestle.oscal.common import TaskValidValues',
        'from trestle.oscal.common import TokenDatatype',
    ],
    'catalog': [
        'from trestle.oscal.common import Parameter1, Parameter2',
        'from trestle.oscal.common import StringDatatype',
    ],
    'common': [],
    'component': [
        'from trestle.oscal.common import StringDatatype',
        'from trestle.oscal.common import URIReferenceDatatype',
    ],
    'mapping': [
        'from trestle.oscal.common import StringDatatype',
        'from trestle.oscal.common import TokenDatatype',
        'from trestle.oscal.common import URIDatatype',
    ],
    'poam': [
        'from trestle.oscal.common import RelatedObservation',
        'from trestle.oscal.common import StringDatatype',
        'from trestle.oscal.common import TaskValidValues',
        'from trestle.oscal.common import TokenDatatype',
        'from trestle.oscal.common import RelatedObservation as RelatedObservation1',
    ],
    'profile': [
        'from trestle.oscal.common import Parameter1, Parameter2',
        'from trestle.oscal.common import StringDatatype',
    ],
    'ssp': [
        'from trestle.oscal.common import StringDatatype',
        'from trestle.oscal.common import Status, SystemComponent',
    ],
}


def bkwd_compat_1_0_4(fstem):
    """Backward compatibility for items moved into common in 1.1.2."""
    lines = []
    if fstem in additions.keys():
        fname = f'trestle/oscal/{fstem}.py'
        with open(fname, 'r') as f:
            for line in f:
                lines.append(line)
                if 'import trestle.oscal.common as common' in line:
                    for item in additions[fstem]:
                        line = f'{item}\n'
                        lines.append(line)
                        logger.debug(f'bkwd_compat_1_0_4: file {fstem}.py insert "{line.strip()}"')
        with open(fname, 'w') as f:
            for line in lines:
                f.write(line)


def pydantic_interface_v1(fstem):
    """Patch for trestle use of pydantic v1 interface from pydantic v2 lib."""
    # This function should be removed once the v2 interface is supported in trestle.
    lines = []
    if fstem in additions.keys():
        fname = f'trestle/oscal/{fstem}.py'
        with open(fname, 'r') as f:
            for line in f:
                if line.startswith('from pydantic'):
                    line = line.replace('pydantic', 'pydantic.v1')
                    logger.debug(f'pydantic_interface_v1: file {fstem}.py modify "{line.strip()}"')
                lines.append(line)
        with open(fname, 'w') as f:
            for line in lines:
                f.write(line)


def apply_eligible(line):
    """Apply eligible for token replacement.

    We want to replace class names in type annotations but not in string literals.
    For __root__ lines with Field(...), we need to replace class names in the type
    annotation (before = Field) but not in the description/title strings.
    """
    # If no title= or description=, always eligible
    if 'title=' not in line and 'description=' not in line:
        return True

    # Special case for CommonRiskStatus
    if 'CommonRiskStatus' in line:
        return True

    # For __root__ lines with type annotations, we want to replace class names
    # in the type annotation part only (before ' = Field(')
    if '__root__:' in line and ' = Field(' in line:
        return True

    # Otherwise, skip lines with title=/description= to avoid changing strings
    return False


def apply_changes_to_class_list(classes, changes):
    """Make all changes to the name and body of a list of classes."""
    for i, c in enumerate(classes):
        lines = []
        for line in c.lines:
            if apply_eligible(line):
                for item in changes:
                    if item[0] in line:
                        line = replace_token(line, item[0], item[1])
            lines.append(line)
        classes[i].lines = lines

        # make sure class definition has correct name
        paren = lines[0].find('(')
        class_name = classes[i].name
        if paren > 0:
            class_name = lines[0][len('class ') : paren]
        classes[i].name = class_name
        # need to regenerate body since tokens changed
        classes[i].generate_body_text()
    return classes


def apply_changes_to_classes(file_classes, changes, com_names):
    """Apply changes to dict of classes organized by file."""
    for fc in file_classes.items():
        classes = fc[1]
        for i, c in enumerate(classes):
            lines = []
            for line in c.lines:
                if 'title=' not in line and 'description=' not in line:
                    for item in changes.items():
                        if item[0] not in line:
                            continue
                        new_name = item[1]
                        # if not in common then need to add common. to common names
                        if fc[0] != 'common' and new_name in com_names:
                            tentative_name = 'common.' + new_name
                            if tentative_name not in line:
                                new_name = tentative_name
                        line = replace_token(line, item[0], new_name)
                lines.append(line)
            classes[i].lines = lines

            # class name may have been replaced by change - so update with new name
            paren = lines[0].find('(')
            class_name = classes[i].name
            if paren > 0:
                class_name = lines[0][len('class ') : paren]
            classes[i].name = class_name
            classes[i].generate_body_text()
        file_classes[fc[0]] = classes
    return file_classes


def reorder_and_dump_as_python(file_classes):
    """Reorder the files and dump."""
    for item in file_classes.items():
        ordered, forward_refs = reorder_classes(item[0], item[1])
        # Keep forward_refs for classes with circular dependencies
        write_oscal(ordered, forward_refs, item[0])
        bkwd_compat_1_0_4(item[0])
        pydantic_interface_v1(item[0])


def find_full_changes(file_classes):
    """Find all name changes and what files made them."""
    changes = {}
    com_names = []
    for c in file_classes['common']:
        changes[c.unique_name] = c.name
        com_names.append(c.name)
    for fstem in fstems:
        for c in file_classes[fstem]:
            changes[c.unique_name] = c.name
    return changes, com_names


def kill_min_items(classes):
    """Kill all references to min_items=1."""
    # NOTE!  This changes all constr list to normal List
    for i, c in enumerate(classes):
        for j, line in enumerate(c.lines):
            c.lines[j] = line.replace(', min_items=1', '')
        classes[i] = c
    return classes


def fix_include_all(classes):
    """Replace [IncludeAll] with [Any]."""
    for i, c in enumerate(classes):
        for j, line in enumerate(c.lines):
            c.lines[j] = line.replace('[IncludeAll]', '[Any]')
        classes[i] = c
    return classes


def fix_regexes(classes):
    """Replace all regex not supported by python."""
    bad_regex = '^(\\p{L}|_)(\\p{L}|\\p{N}|[.\\-_])*$'
    good_regex = '^[_A-Za-z\\u00C0-\\u00D6\\u00D8-\\u00F6\\u00F8-\\u02FF\\u0370-\\u037D\\u037F-\\u1FFF\\u200C-\\u200D\\u2070-\\u218F\\u2C00-\\u2FEF\\u3001-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFFD][_A-Za-z\\u00C0-\\u00D6\\u00D8-\\u00F6\\u00F8-\\u02FF\\u0370-\\u037D\\u037F-\\u1FFF\\u200C-\\u200D\\u2070-\\u218F\\u2C00-\\u2FEF\\u3001-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFFD\\-\\.0-9\\u00B7\\u0300-\\u036F\\u203F-\\u2040]*$'  # noqa E501
    for i, c in enumerate(classes):
        for j, line in enumerate(c.lines):
            c.lines[j] = line.replace(bad_regex, good_regex)
        classes[i] = c
    return classes


def strip_file(classes):
    """Given set of classes from a file strip all names and apply changes to references in the bodies."""
    classes = strip_prefixes(classes)
    changes = []
    for c in classes:
        changes.append((c.original_name, c.name))
    return apply_changes_to_class_list(classes, changes)


def _strip_all_files(file_classes):
    for item in file_classes.items():
        stem = item[0]
        if item[0] != 'common':
            file_classes[stem] = strip_file(file_classes[stem])
    return file_classes


def update_refs_per_file(classes):
    """Change all refs to the _ versions."""
    changes = []
    for c in classes:
        if '_' in c.name:
            changes.append((c.name.split('_')[1], c.name))
    classes = apply_changes_to_class_list(classes, changes)
    return classes


def _strip_unrefed_files(file_class):
    """
    Strip unreferenced classes from each oscal file.

    The generated oscal files include classes that aren't referenced within the file.
    Those classes need to be removed early since they shouldn't be there at all.
    A key problem class is SetParameter, but there are others.
    This does a simple check of the file name being present at all in the body other classes.
    It could instead be a token-based search but this seems sufficient.
    """
    dead_names = []
    for c in file_class:
        if c.name == 'Model':
            continue
        refd = False
        for d in file_class:
            if d.name in [c.name] + dead_names:
                continue
            if c.name in d.body_text:
                refd = True
                break
        if not refd:
            dead_names.append(c.name)
    return [c for c in file_class if c.name not in dead_names]


def patch_lines(c, old, new):
    """Patch lines."""
    for ii in range(1, len(c.lines)):
        line = c.lines[ii]
        line = line.replace(old, new, 1)
        c.lines[ii] = line
    return c.lines


def patch_items(file_classes):
    """Patch items."""
    for key in file_classes:
        file_class = file_classes[key]
        for c in file_class:
            if c.name == 'EmailAddress':
                c.lines = patch_lines(c, 'EmailAddressDatatype', 'EmailStr')
            # see: schema_preprocess patch_finding_target
            elif c.name == 'FindingTarget':
                c.lines = patch_lines(c, 'objective_status', 'status')
            # see: schema_preprocess patch_poam_origins
            elif c.name == 'PoamItem':
                c.lines = patch_lines(c, 'originations', 'origins')
    return file_classes


def kill_roots(file_classes):
    """Kill the root classes in common."""
    com = file_classes['common']
    root_classes = {}
    match_str = ':__root__:'
    # find all root classes
    for c in com:
        body = c.body_text
        if body.startswith(match_str):
            p_field = body.find('=Field(')
            if p_field > 0:
                body = body[:p_field]
            root_classes[c.name] = body[len(match_str) :]
    new_root_classes = {}
    skip_class_names = ['IntegerDatatype', 'NonNegativeIntegerDatatype', 'PositiveIntegerDatatype', 'OscalVersion']
    # replace references to root classes in the root classes
    for name, body in root_classes.items():
        if body in root_classes:
            body = root_classes[body]
        # now have mapping of root class name to its simplified body
        if name not in skip_class_names:
            new_root_classes[name] = body
    for classes in file_classes.values():
        for c in classes:
            if c.name not in new_root_classes:
                for ii in range(1, len(c.lines)):
                    line = c.lines[ii]
                    for name, body in new_root_classes.items():
                        # handle special cases
                        if 'NonNegativeIntegerDatatype' in line:
                            line = line.replace('NonNegativeIntegerDatatype', 'conint(ge=0, multiple_of=1)', 1)
                        if 'PositiveIntegerDatatype' in line:
                            line = line.replace('PositiveIntegerDatatype', 'conint(ge=1, multiple_of=1)', 1)
                        if 'IntegerDatatype' in line:
                            line = line.replace('IntegerDatatype', 'conint(multiple_of=1)', 1)
                        if c.name == 'OscalVersion':
                            if any(token in line for token in [' __root__: StringDatatype']):
                                line = line.replace(name, body, 1)
                            continue
                        if any(
                            token in line
                            for token in [
                                'id: TokenDatatype',
                                'value: StringDatatype',
                                'uuid: UUIDDatatype',
                                'uuid: Optional[UUIDDatatype]',
                                'source: URIReferenceDatatype',
                                'type: Union[StringDatatype, DefinedComponentTypeValidValues]',
                                'type: Union[StringDatatype, SystemComponentTypeValidValues]',
                            ]
                        ):
                            line = line.replace(name, body, 1)
                            continue
                        if 'title=' in line and 'Value' in line:
                            continue
                        if 'OscalVersion' not in line and 'OSCAL' not in line:
                            line = line.replace('common.' + name, body, 1)
                            if name not in body:
                                line = line.replace(name, body, 1)
                    c.lines[ii] = line
    return file_classes


def normalize_files():
    """Clean up classes to minimise cross reference."""
    all_classes = load_all_classes()

    # kill the min_items immediately
    uc = kill_min_items(all_classes)

    # fix IncludeAll that isn't defined properly in schema
    uc = fix_include_all(all_classes)

    # fix non-supported regexes
    uc = fix_regexes(all_classes)

    # organize in a dict with filename as key
    file_classes = _list_to_file_classes(all_classes)

    # strip all names and bodies
    file_classes = _strip_all_files(file_classes)

    # strip classes that are never used in file
    for name, file_class in file_classes.items():
        file_classes[name] = _strip_unrefed_files(file_class)

    # convert dict to single list of classes with expected duplicates
    uc = _file_classes_to_list(file_classes, True)

    # find all unique classes based on body text
    uc = find_unique_classes(uc)

    # find classes with same name and different bodies - and modify class names with _
    # bodies are not changed
    uc = fix_clashes(uc)
    # now have unique list of classes with unique names
    # some names have _ in them to be removed later

    # make sure all classes have the proper unique name set at this point
    for c in uc:
        c.unique_name = c.name

    # some class names have _ in them, so change refs in each file to include the _
    uc = update_refs_per_file(uc)

    # split the classes based on current name and whether referenced by only one file
    file_classes = split_classes(uc)

    # find all changes from old name to new
    changes, com_names = find_full_changes(file_classes)

    # now apply all the changes to the class bodies
    file_classes = apply_changes_to_classes(file_classes, changes, com_names)

    # patch common items
    file_classes = patch_items(file_classes)

    # kill the __root__ classes
    file_classes = kill_roots(file_classes)

    # re-order them in each file and dump
    reorder_and_dump_as_python(file_classes)

    # this will leave files with raw formatting and make code-format must be run separately


if __name__ == '__main__':
    """Main invocation."""
    normalize_files()
