# -*- mode:python; coding:utf-8 -*-
# Copyright (c) 2020 IBM Corp. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
#
####### DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT ######
#                                                                        #
#        This file is automatically generated by gen_oscal.py            #
#                                                                        #
####### DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT ######
#
#
from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import StringConstraints, AnyUrl, AwareDatetime, ConfigDict, EmailStr, Extra, Field, RootModel, conint, model_validator

from trestle.core.base_model import OscalBaseModel
from trestle.oscal import OSCAL_VERSION_REGEX, OSCAL_VERSION
from typing_extensions import Annotated


NonNegativeIntegerDatatype = OscalBaseModel
PositiveIntegerDatatype = OscalBaseModel
EmailAddressDatatype = OscalBaseModel


class UUIDDatatype(RootModel[Annotated[str, StringConstraints(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$')]]):
    root: Annotated[str, StringConstraints(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$')] = Field(..., description="A type 4 ('random' or 'pseudorandom') or type 5 UUID per RFC 4122.")


class URIReferenceDatatype(RootModel[str]):
    root: str = Field(..., description='A URI Reference, either a URI or a relative-reference, formatted according to section 4.1 of RFC3986.')


class URIDatatype(RootModel[AnyUrl]):
    root: AnyUrl = Field(..., description='A universal resource identifier (URI) formatted according to RFC3986.')


class TokenDatatype(RootModel[Annotated[str, StringConstraints(pattern=r'^[_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD][_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\-\.0-9\u00B7\u0300-\u036F\u203F-\u2040]*$')]]):
    root: Annotated[str, StringConstraints(pattern=r'^[_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD][_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\-\.0-9\u00B7\u0300-\u036F\u203F-\u2040]*$')] = Field(..., description='A non-colonized name as defined by XML Schema Part 2: Datatypes Second Edition. https://www.w3.org/TR/xmlschema11-2/#NCName.')


class TimeUnitValidValues(Enum):
    seconds = 'seconds'
    minutes = 'minutes'
    hours = 'hours'
    days = 'days'
    months = 'months'
    years = 'years'


class ThreatIdValidValues(Enum):
    http___fedramp_gov = 'http://fedramp.gov'
    http___fedramp_gov_ns_oscal = 'http://fedramp.gov/ns/oscal'


class ThreatId(OscalBaseModel):
    """
    A pointer, by ID, to an externally-defined threat.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    system: Union[URIDatatype, ThreatIdValidValues] = Field(..., description='Specifies the source of the threat information.', title='Threat Type Identification System')
    href: Optional[URIReferenceDatatype] = Field(None, description='An optional location for the threat data, from which this ID originates.', title='Threat Information Resource Reference')
    id: URIDatatype


class TelephoneTypeValidValues(Enum):
    home = 'home'
    office = 'office'
    mobile = 'mobile'


class TaskValidValues(Enum):
    milestone = 'milestone'
    action = 'action'


class SystemComponentTypeValidValues(Enum):
    this_system = 'this-system'
    system = 'system'
    interconnection = 'interconnection'
    software = 'software'
    hardware = 'hardware'
    service = 'service'
    policy = 'policy'
    physical = 'physical'
    process_procedure = 'process-procedure'
    plan = 'plan'
    guidance = 'guidance'
    standard = 'standard'
    validation = 'validation'
    network = 'network'


class SystemComponentOperationalStateValidValues(Enum):
    under_development = 'under-development'
    operational = 'operational'
    disposition = 'disposition'
    other = 'other'


class SubjectReferenceValidValues(Enum):
    component = 'component'
    inventory_item = 'inventory-item'
    location = 'location'
    party = 'party'
    user = 'user'
    resource = 'resource'


class StringDatatype(RootModel[Annotated[str, StringConstraints(pattern=r'^\S(.*\S)?$')]]):
    root: Annotated[str, StringConstraints(pattern=r'^\S(.*\S)?$')] = Field(..., description='A non-empty string with leading and trailing whitespace disallowed. Whitespace is: U+9, U+10, U+32 or [ \n\t]+')


class State(Enum):
    """
    Identifies the implementation status of the control or control objective.
    """

    implemented = 'implemented'
    partial = 'partial'
    planned = 'planned'
    alternative = 'alternative'
    not_applicable = 'not-applicable'


class Source(OscalBaseModel):
    """
    Assessment subjects will be identified while conducting the referenced activity-instance.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    task_uuid: UUIDDatatype = Field(
        ...,
        alias='task-uuid',
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference (in this or other OSCAL instances) an assessment activity to be performed as part of the event. The locally defined UUID of the task can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Task Universally Unique Identifier',
    )


class SelectSubjectByIdValidValues(Enum):
    component = 'component'
    inventory_item = 'inventory-item'
    location = 'location'
    party = 'party'
    user = 'user'
    resource = 'resource'


class SelectObjectiveById(OscalBaseModel):
    """
    Used to select a control objective for inclusion/exclusion based on the control objective's identifier.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    objective_id: TokenDatatype = Field(..., alias='objective-id', description='Points to an assessment objective.', title='Objective ID')


class SelectControlById(OscalBaseModel):
    """
    Used to select a control for inclusion/exclusion based on one or more control identifiers. A set of statement identifiers can be used to target the inclusion/exclusion to only specific control statements providing more granularity over the specific statements that are within the asessment scope.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    control_id: TokenDatatype = Field(..., alias='control-id', description='A reference to a control with a corresponding id value. When referencing an externally defined control, the Control Identifier Reference must be used in the context of the external / imported OSCAL instance (e.g., uri-reference).', title='Control Identifier Reference')
    statement_ids: Optional[List[TokenDatatype]] = Field(None, alias='statement-ids', min_length=1)


class RoleId(RootModel[TokenDatatype]):
    root: TokenDatatype = Field(..., description='Reference to a role by UUID.', title='Role Identifier Reference')


class RiskStatusValidValues(Enum):
    open = 'open'
    investigating = 'investigating'
    remediating = 'remediating'
    deviation_requested = 'deviation-requested'
    deviation_approved = 'deviation-approved'
    closed = 'closed'


class RiskStatus(RootModel[Union[TokenDatatype, RiskStatusValidValues]]):
    root: Union[TokenDatatype, RiskStatusValidValues] = Field(..., description='Describes the status of the associated risk.', title='Risk Status')


class Remarks(RootModel[str]):
    root: str = Field(..., description='Additional commentary about the containing object.', title='Remarks')


class RelatedRisk(OscalBaseModel):
    """
    Relates the finding to a set of referenced risks that were used to determine the finding.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    risk_uuid: UUIDDatatype = Field(..., alias='risk-uuid', description='A machine-oriented identifier reference to a risk defined in the list of risks.', title='Risk Universally Unique Identifier Reference')


class RelatedObservation(OscalBaseModel):
    """
    Relates the finding to a set of referenced observations that were used to determine the finding.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    observation_uuid: UUIDDatatype = Field(..., alias='observation-uuid', description='A machine-oriented identifier reference to an observation defined in the list of observations.', title='Observation Universally Unique Identifier Reference')


class Rel(Enum):
    """
    Describes the type of relationship provided by the link's hypertext reference. This can be an indicator of the link's purpose.
    """

    reference = 'reference'


class Reason(Enum):
    """
    The reason the objective was given it's status.
    """

    pass_ = 'pass'
    fail = 'fail'
    other = 'other'


class Property(OscalBaseModel):
    """
    An attribute, characteristic, or quality of the containing object expressed as a namespace qualified name/value pair.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: TokenDatatype = Field(..., description="A textual label, within a namespace, that identifies a specific attribute, characteristic, or quality of the property's containing object.", title='Property Name')
    uuid: Optional[UUIDDatatype] = Field(None, description='A unique identifier for a property.', title='Property Universally Unique Identifier')
    ns: Optional[URIDatatype] = Field(None, description="A namespace qualifying the property's name. This allows different organizations to associate distinct semantics with the same name.", title='Property Namespace')
    value: StringDatatype = Field(..., description='Indicates the value of the attribute, characteristic, or quality.', title='Property Value')
    class_: Optional[TokenDatatype] = Field(None, alias='class', description="A textual label that provides a sub-type or characterization of the property's name.", title='Property Class')
    group: Optional[TokenDatatype] = Field(None, description='An identifier for relating distinct sets of properties.', title='Property Group')
    remarks: Optional[Remarks] = None


class PortRangeValidValues(Enum):
    TCP = 'TCP'
    UDP = 'UDP'


class PortRange(OscalBaseModel):
    """
    Where applicable this is the transport layer protocol port range an IPv4-based or IPv6-based service uses.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    start: Optional[NonNegativeIntegerDatatype] = Field(None, description='Indicates the starting port number in a port range for a transport layer protocol', title='Start')
    end: Optional[NonNegativeIntegerDatatype] = Field(None, description='Indicates the ending port number in a port range for a transport layer protocol', title='End')
    transport: Optional[PortRangeValidValues] = Field(None, description='Indicates the transport type.', title='Transport')


class PartyUuid(RootModel[UUIDDatatype]):
    root: UUIDDatatype = Field(..., description='Reference to a party by UUID.', title='Party Universally Unique Identifier Reference')


class PartyTypeValidValues(Enum):
    person = 'person'
    organization = 'organization'


class ParameterValue(RootModel[StringDatatype]):
    root: StringDatatype = Field(..., description='A parameter value or set of values.', title='Parameter Value')


class ParameterGuideline(OscalBaseModel):
    """
    A prose statement that provides a recommendation for the use of a parameter.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    prose: str = Field(..., description='Prose permits multiple paragraphs, lists, tables etc.', title='Guideline Text')


class OscalVersion(RootModel[StringDatatype]):
    root: StringDatatype = Field(..., description='The OSCAL model version the document was authored against and will conform to as valid.', title='OSCAL Version')




    @model_validator(mode='after')
    def oscal_version_is_valid(cls, model: 'OscalVersion') -> 'OscalVersion':
        v = model.root # Access the underlying value via .root
        strict_version = False
        if not strict_version:
            return model # Return the model instance

class OriginActorValidValues(Enum):
    tool = 'tool'
    assessment_platform = 'assessment-platform'
    party = 'party'


class ObservationTypeValidValues(Enum):
    ssp_statement_issue = 'ssp-statement-issue'
    control_objective = 'control-objective'
    mitigation = 'mitigation'
    finding = 'finding'
    historic = 'historic'


class ObjectiveStatusStateValidValues(Enum):
    satisfied = 'satisfied'
    not_satisfied = 'not-satisfied'


class ObjectiveStatus(OscalBaseModel):
    """
    A determination of if the objective is satisfied or not within a given system.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    state: ObjectiveStatusStateValidValues = Field(..., description='An indication as to whether the objective is satisfied or not.', title='Objective Status State')
    reason: Optional[Union[TokenDatatype, Reason]] = Field(None, description="The reason the objective was given it's status.", title='Objective Status Reason')
    remarks: Optional[Remarks] = None


class NamingSystemValidValues(Enum):
    http___fedramp_gov = 'http://fedramp.gov'
    http___fedramp_gov_ns_oscal = 'http://fedramp.gov/ns/oscal'
    http___csrc_nist_gov_ns_oscal = 'http://csrc.nist.gov/ns/oscal'
    http___csrc_nist_gov_ns_oscal_unknown = 'http://csrc.nist.gov/ns/oscal/unknown'
    http___cve_mitre_org = 'http://cve.mitre.org'
    http___www_first_org_cvss_v2_0 = 'http://www.first.org/cvss/v2.0'
    http___www_first_org_cvss_v3_0 = 'http://www.first.org/cvss/v3.0'
    http___www_first_org_cvss_v3_1 = 'http://www.first.org/cvss/v3.1'
    https___www_first_org_cvss_v4_0 = 'https://www.first.org/cvss/v4-0'


class Name(Enum):
    """
    A textual label that uniquely identifies the part's semantic type.
    """

    asset = 'asset'
    method = 'method'
    objective = 'objective'


class Methods(Enum):
    """
    Identifies how the observation was made.
    """

    EXAMINE = 'EXAMINE'
    INTERVIEW = 'INTERVIEW'
    TEST = 'TEST'
    UNKNOWN = 'UNKNOWN'


class LoggedBy(OscalBaseModel):
    """
    Used to indicate who created a log entry in what role.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    party_uuid: UUIDDatatype = Field(..., alias='party-uuid', description='A machine-oriented identifier reference to the party who is making the log entry.', title='Party UUID Reference')
    role_id: Optional[TokenDatatype] = Field(None, alias='role-id', description='A point to the role-id of the role in which the party is making the log entry.', title='Actor Role')


class LocationUuid(RootModel[UUIDDatatype]):
    root: UUIDDatatype = Field(..., description='Reference to a location by UUID.', title='Location Universally Unique Identifier Reference')


class Link(OscalBaseModel):
    """
    A reference to a local or remote resource, that has a specific relation to the containing object.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    href: URIReferenceDatatype = Field(..., description='A resolvable URL reference to a resource.', title='Hypertext Reference')
    rel: Optional[Union[TokenDatatype, Rel]] = Field(None, description="Describes the type of relationship provided by the link's hypertext reference. This can be an indicator of the link's purpose.", title='Link Relation Type')
    media_type: Optional[StringDatatype] = Field(None, alias='media-type', description='A label that indicates the nature of a resource, as a data serialization or format.', title='Media Type')
    resource_fragment: Optional[StringDatatype] = Field(None, alias='resource-fragment', description='In case where the href points to a back-matter/resource, this value will indicate the URI fragment to append to any rlink associated with the resource. This value MUST be URI encoded.', title='Resource Fragment')
    text: Optional[str] = Field(None, description='A textual label to associate with the link, which may be used for presentation in a tool.', title='Link Text')


class Lifecycle(Enum):
    """
    Identifies whether this is a recommendation, such as from an assessor or tool, or an actual plan accepted by the system owner.
    """

    recommendation = 'recommendation'
    planned = 'planned'
    completed = 'completed'


class JsonSchemaDirective(RootModel[URIReferenceDatatype]):
    root: URIReferenceDatatype = Field(..., description='A JSON Schema directive to bind a specific schema to its document instance.', title='Schema Directive')


class IntegerDatatype(RootModel[int]):
    root: int = Field(..., description='A whole number value.')


class IncludeAll(OscalBaseModel):
    """
    Include all controls from the imported catalog or profile resources.
    """

    model_config = ConfigDict(
        extra='forbid',
    )


class ImportSsp(OscalBaseModel):
    """
    Used by the assessment plan and POA&M to import information about the system.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    href: URIReferenceDatatype = Field(..., description='A resolvable URL reference to the system security plan for the system being assessed.', title='System Security Plan Reference')
    remarks: Optional[Remarks] = None


class ImplementationStatus(OscalBaseModel):
    """
    Indicates the degree to which the a given control is implemented.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    state: Union[TokenDatatype, State] = Field(..., description='Identifies the implementation status of the control or control objective.', title='Implementation State')
    remarks: Optional[Remarks] = None


class IdentifierType(Enum):
    """
    Identifies the identification system from which the provided identifier was assigned.
    """

    https___fedramp_gov = 'https://fedramp.gov'
    http___fedramp_gov_ns_oscal = 'http://fedramp.gov/ns/oscal'
    https___ietf_org_rfc_rfc4122 = 'https://ietf.org/rfc/rfc4122'
    http___ietf_org_rfc_rfc4122 = 'http://ietf.org/rfc/rfc4122'


class HowManyValidValues(Enum):
    one = 'one'
    one_or_more = 'one-or-more'


HowMany = HowManyValidValues


class FunctionPerformed(RootModel[StringDatatype]):
    root: StringDatatype = Field(..., description='Describes a function performed for a given authorized privilege by this user class.', title='Functions Performed')


class FindingTargetTypeValidValues(Enum):
    statement_id = 'statement-id'
    objective_id = 'objective-id'


class FindingTarget(OscalBaseModel):
    """
    Captures an assessor's conclusions regarding the degree to which an objective is satisfied.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: FindingTargetTypeValidValues = Field(..., description='Identifies the type of the target.', title='Finding Target Type')
    target_id: TokenDatatype = Field(..., alias='target-id', description='A machine-oriented identifier reference for a specific target qualified by the type.', title='Finding Target Identifier Reference')
    title: Optional[str] = Field(None, description='The title for this objective status.', title='Objective Status Title')
    description: Optional[str] = Field(None, description="A human-readable description of the assessor's conclusions regarding the degree to which an objective is satisfied.", title='Objective Status Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    implementation_status: Optional[ImplementationStatus] = Field(None, alias='implementation-status')
    remarks: Optional[Remarks] = None
    status: Optional[ObjectiveStatus] = Field(None, description='A determination of if the objective is satisfied or not within a given system.', title='Objective Status')


class Facet(OscalBaseModel):
    """
    An individual characteristic that is part of a larger set produced by the same actor.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: TokenDatatype = Field(..., description='The name of the risk metric within the specified system.', title='Facet Name')
    system: Union[URIDatatype, NamingSystemValidValues] = Field(..., description='Specifies the naming system under which this risk metric is organized, which allows for the same names to be used in different systems controlled by different parties. This avoids the potential of a name clash.', title='Naming System')
    value: StringDatatype = Field(..., description='Indicates the value of the facet.', title='Facet Value')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class ExternalSchemeValidValues(Enum):
    http___orcid_org_ = 'http://orcid.org/'


class ExternalId(OscalBaseModel):
    """
    An identifier for a person or organization using a designated scheme. e.g. an Open Researcher and Contributor ID (ORCID).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    scheme: Union[URIDatatype, ExternalSchemeValidValues] = Field(..., description='Indicates the type of external identifier.', title='External Identifier Schema')
    id: StringDatatype


class EmailAddress(RootModel[EmailAddressDatatype]):
    root: EmailStr = Field(..., description='An email address as defined by RFC 5322 Section 3.4.1.', title='Email Address')


class DocumentSchemeValidValues(Enum):
    http___www_doi_org_ = 'http://www.doi.org/'


class DocumentId(OscalBaseModel):
    """
    A document identifier qualified by an identifier scheme.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    scheme: Optional[Union[URIDatatype, DocumentSchemeValidValues]] = Field(None, description='Qualifies the kind of document identifier using a URI. If the scheme is not provided the value of the element will be interpreted as a string of characters.', title='Document Identification Scheme')
    identifier: StringDatatype


class Dependency(OscalBaseModel):
    """
    Used to indicate that a task is dependent on another task.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    task_uuid: UUIDDatatype = Field(..., alias='task-uuid', description='A machine-oriented identifier reference to a unique task.', title='Task Universally Unique Identifier Reference')
    remarks: Optional[Remarks] = None


class DateTimeWithTimezoneDatatype(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(..., description='A string representing a point in time with a required timezone.')


class ControlSelection(OscalBaseModel):
    """
    Identifies the controls being assessed. In the assessment plan, these are the planned controls. In the assessment results, these are the actual controls, and reflects any changes from the plan.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(None, description='A human-readable description of in-scope controls specified for assessment.', title='Assessed Controls Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    include_all: Optional[IncludeAll] = Field(None, alias='include-all')
    include_controls: Optional[List[SelectControlById]] = Field(None, alias='include-controls', min_length=1)
    exclude_controls: Optional[List[SelectControlById]] = Field(None, alias='exclude-controls', min_length=1)
    remarks: Optional[Remarks] = None


class ControlObjectiveSelection(OscalBaseModel):
    """
    Identifies the control objectives of the assessment. In the assessment plan, these are the planned objectives. In the assessment results, these are the assessed objectives, and reflects any changes from the plan.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(None, description='A human-readable description of this collection of control objectives.', title='Control Objectives Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    include_all: Optional[IncludeAll] = Field(None, alias='include-all')
    include_objectives: Optional[List[SelectObjectiveById]] = Field(None, alias='include-objectives', min_length=1)
    exclude_objectives: Optional[List[SelectObjectiveById]] = Field(None, alias='exclude-objectives', min_length=1)
    remarks: Optional[Remarks] = None


class Citation(OscalBaseModel):
    """
    An optional citation consisting of end note text using structured markup.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: str = Field(..., description='A line of citation text.', title='Citation Text')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)


class Base64Datatype(RootModel[Annotated[str, StringConstraints(pattern=r'^[0-9A-Za-z+/]+={0,2}$')]]):
    root: Annotated[str, StringConstraints(pattern=r'^[0-9A-Za-z+/]+={0,2}$')] = Field(..., description='Binary data encoded using the Base 64 encoding algorithm as defined by RFC4648.')


class Base64(OscalBaseModel):
    """
    A resource encoded using the Base64 alphabet defined by RFC 2045.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    filename: Optional[TokenDatatype] = Field(None, description='Name of the file before it was encoded as Base64 to be embedded in a resource. This is the name that will be assigned to the file when the file is decoded.', title='File Name')
    media_type: Optional[StringDatatype] = Field(None, alias='media-type', description='A label that indicates the nature of a resource, as a data serialization or format.', title='Media Type')
    value: Base64Datatype


class AuthorizedPrivilege(OscalBaseModel):
    """
    Identifies a specific system privilege held by the user, along with an associated description and/or rationale for the privilege.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., description='A human readable name for the privilege.', title='Privilege Title')
    description: Optional[str] = Field(None, description="A summary of the privilege's purpose within the system.", title='Privilege Description')
    functions_performed: List[FunctionPerformed] = Field(..., alias='functions-performed', min_length=1)


class AtFrequency(OscalBaseModel):
    """
    The task is intended to occur at the specified frequency.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    period: PositiveIntegerDatatype = Field(..., description='The task must occur after the specified period has elapsed.', title='Period')
    unit: TimeUnitValidValues = Field(..., description='The unit of time for the period.', title='Time Unit')


class AssessmentSubjectValidValues(Enum):
    component = 'component'
    inventory_item = 'inventory-item'
    location = 'location'
    party = 'party'
    user = 'user'


class AssessmentSubjectPlaceholder(OscalBaseModel):
    """
    Used when the assessment subjects will be determined as part of one or more other assessment activities. These assessment subjects will be recorded in the assessment results in the assessment log.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier for a set of assessment subjects that will be identified by a task or an activity that is part of a task. The locally defined UUID of the assessment subject placeholder can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Assessment Subject Placeholder Universally Unique Identifier',
    )
    description: Optional[str] = Field(None, description='A human-readable description of intent of this assessment subject placeholder.', title='Assessment Subject Placeholder Description')
    sources: List[Source] = Field(..., min_length=1)
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class AssessmentPart(OscalBaseModel):
    """
    A partition of an assessment plan or results or a child of another part.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: Optional[UUIDDatatype] = Field(
        None, description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this part elsewhere in this or other OSCAL instances. The locally defined UUID of the part can be used to reference the data item locally or globally (e.g., in an ported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.', title='Part Identifier'
    )
    name: Union[TokenDatatype, Name] = Field(..., description="A textual label that uniquely identifies the part's semantic type.", title='Part Name')
    ns: Optional[URIDatatype] = Field(None, description="A namespace qualifying the part's name. This allows different organizations to associate distinct semantics with the same name.", title='Part Namespace')
    class_: Optional[TokenDatatype] = Field(None, alias='class', description="A textual label that provides a sub-type or characterization of the part's name. This can be used to further distinguish or discriminate between the semantics of multiple parts of the same control with the same name and ns.", title='Part Class')
    title: Optional[str] = Field(None, description='A name given to the part, which may be used by a tool for display and navigation.', title='Part Title')
    props: Optional[List[Property]] = Field(None, min_length=1)
    prose: Optional[str] = Field(None, description='Permits multiple paragraphs, lists, tables etc.', title='Part Text')
    parts: Optional[List[AssessmentPart]] = None
    links: Optional[List[Link]] = Field(None, min_length=1)


class Algorithm(Enum):
    """
    The digest method by which a hash is derived.
    """

    SHA_224 = 'SHA-224'
    SHA_256 = 'SHA-256'
    SHA_384 = 'SHA-384'
    SHA_512 = 'SHA-512'
    SHA3_224 = 'SHA3-224'
    SHA3_256 = 'SHA3-256'
    SHA3_384 = 'SHA3-384'
    SHA3_512 = 'SHA3-512'


class AddressTypeValidValues(Enum):
    home = 'home'
    work = 'work'


class AddrLine(RootModel[StringDatatype]):
    root: StringDatatype = Field(..., description='A single line of an address.', title='Address line')


class WithinDateRange(OscalBaseModel):
    """
    The task is intended to occur within the specified date range.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    start: DateTimeWithTimezoneDatatype = Field(..., description='The task must occur on or after the specified date.', title='Start Date Condition')
    end: DateTimeWithTimezoneDatatype = Field(..., description='The task must occur on or before the specified date.', title='End Date Condition')


class Version(RootModel[StringDatatype]):
    root: StringDatatype = Field(..., description='Used to distinguish a specific revision of an OSCAL document from other previous and future versions.', title='Document Version')


class Test(OscalBaseModel):
    """
    A test expression which is expected to be evaluated by a tool.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    expression: StringDatatype = Field(..., description='A formal (executable) expression of a constraint.', title='Constraint test')
    remarks: Optional[Remarks] = None


class ParameterConstraint(OscalBaseModel):
    """
    A formal or informal expression of a constraint or test.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(None, description='A textual summary of the constraint to be applied.', title='Constraint Description')
    tests: Optional[List[Test]] = Field(None, min_length=1)


class TelephoneNumber(OscalBaseModel):
    """
    A telephone service number as defined by ITU-T E.164.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Optional[Union[StringDatatype, TelephoneTypeValidValues]] = Field(None, description='Indicates the type of phone number.', title='type flag')
    number: StringDatatype


class SystemUser(OscalBaseModel):
    """
    A type of user that interacts with the system based on an associated role.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this user class elsewhere in this or other OSCAL instances. The locally defined UUID of the system user can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='User Universally Unique Identifier',
    )
    title: Optional[str] = Field(None, description='A name given to the user, which may be used by a tool for display and navigation.', title='User Title')
    short_name: Optional[StringDatatype] = Field(None, alias='short-name', description='A short common name, abbreviation, or acronym for the user.', title='User Short Name')
    description: Optional[str] = Field(None, description="A summary of the user's purpose within the system.", title='User Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    role_ids: Optional[List[RoleId]] = Field(None, alias='role-ids', min_length=1)
    authorized_privileges: Optional[List[AuthorizedPrivilege]] = Field(None, alias='authorized-privileges', min_length=1)
    remarks: Optional[Remarks] = None


class SystemId(OscalBaseModel):
    """
    A human-oriented, globally unique identifier with cross-instance scope that can be used to reference this system identification property elsewhere in this or other OSCAL instances. When referencing an externally defined system identification, the system identification must be used in the context of the external / imported OSCAL instance (e.g., uri-reference). This string should be assigned per-subject, which means it should be consistently used to identify the same system across revisions of the document.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    identifier_type: Optional[Union[URIDatatype, IdentifierType]] = Field(None, alias='identifier-type', description='Identifies the identification system from which the provided identifier was assigned.', title='Identification System Type')
    id: StringDatatype


class SubjectReference(OscalBaseModel):
    """
    A human-oriented identifier reference to a resource. Use type to indicate whether the identified resource is a component, inventory item, location, user, or something else.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject_uuid: UUIDDatatype = Field(..., alias='subject-uuid', description="A machine-oriented identifier reference to a component, inventory-item, location, party, user, or resource using it's UUID.", title='Subject Universally Unique Identifier Reference')
    type: Union[TokenDatatype, SubjectReferenceValidValues] = Field(..., description='Used to indicate the type of object pointed to by the uuid-ref within a subject.', title='Subject Universally Unique Identifier Reference Type')
    title: Optional[str] = Field(None, description='The title or name for the referenced subject.', title='Subject Reference Title')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class MitigatingFactor(OscalBaseModel):
    """
    Describes an existing mitigating factor that may affect the overall determination of the risk, with an optional link to an implementation statement in the SSP.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this mitigating factor elsewhere in this or other OSCAL instances. The locally defined UUID of the mitigating factor can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Mitigating Factor Universally Unique Identifier',
    )
    implementation_uuid: Optional[UUIDDatatype] = Field(
        None,
        alias='implementation-uuid',
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this implementation statement elsewhere in this or other OSCAL instancess. The locally defined UUID of the implementation statement can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Implementation UUID',
    )
    description: str = Field(..., description='A human-readable description of this mitigating factor.', title='Mitigating Factor Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    subjects: Optional[List[SubjectReference]] = Field(None, min_length=1)


class Status(OscalBaseModel):
    """
    Describes the operational status of the system component.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    state: SystemComponentOperationalStateValidValues = Field(..., description='The operational status.', title='State')
    remarks: Optional[Remarks] = None


class SelectSubjectById(OscalBaseModel):
    """
    Identifies a set of assessment subjects to include/exclude by UUID.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject_uuid: UUIDDatatype = Field(..., alias='subject-uuid', description="A machine-oriented identifier reference to a component, inventory-item, location, party, user, or resource using it's UUID.", title='Subject Universally Unique Identifier Reference')
    type: Union[TokenDatatype, SelectSubjectByIdValidValues] = Field(..., description='Used to indicate the type of object pointed to by the uuid-ref within a subject.', title='Subject Universally Unique Identifier Reference Type')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class AssessmentSubject(OscalBaseModel):
    """
    Identifies system elements being assessed, such as components, inventory items, and locations. In the assessment plan, this identifies a planned assessment subject. In the assessment results this is an actual assessment subject, and reflects any changes from the plan. exactly what will be the focus of this assessment. Any subjects not identified in this way are out-of-scope.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Union[TokenDatatype, AssessmentSubjectValidValues] = Field(..., description='Indicates the type of assessment subject, such as a component, inventory, item, location, or party represented by this selection statement.', title='Subject Type')
    description: Optional[str] = Field(None, description='A human-readable description of the collection of subjects being included in this assessment.', title='Include Subjects Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    include_all: Optional[IncludeAll] = Field(None, alias='include-all')
    include_subjects: Optional[List[SelectSubjectById]] = Field(None, alias='include-subjects', min_length=1)
    exclude_subjects: Optional[List[SelectSubjectById]] = Field(None, alias='exclude-subjects', min_length=1)
    remarks: Optional[Remarks] = None


class Role(OscalBaseModel):
    """
    Defines a function, which might be assigned to a party in a specific situation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: TokenDatatype = Field(..., description='A unique identifier for the role.', title='Role Identifier')
    title: str = Field(..., description='A name given to the role, which may be used by a tool for display and navigation.', title='Role Title')
    short_name: Optional[StringDatatype] = Field(None, alias='short-name', description='A short common name, abbreviation, or acronym for the role.', title='Role Short Name')
    description: Optional[str] = Field(None, description="A summary of the role's purpose and associated responsibilities.", title='Role Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class ReviewedControls(OscalBaseModel):
    """
    Identifies the controls being assessed and their control objectives.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(None, description='A human-readable description of control objectives.', title='Control Objective Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    control_selections: List[ControlSelection] = Field(..., alias='control-selections', min_length=1)
    control_objective_selections: Optional[List[ControlObjectiveSelection]] = Field(None, alias='control-objective-selections', min_length=1)
    remarks: Optional[Remarks] = None


class ResponsibleRole(OscalBaseModel):
    """
    A reference to a role with responsibility for performing a function relative to the containing object, optionally associated with a set of persons and/or organizations that perform that role.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    role_id: TokenDatatype = Field(..., alias='role-id', description='A human-oriented identifier reference to a role performed.', title='Responsible Role ID')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    party_uuids: Optional[List[PartyUuid]] = Field(None, alias='party-uuids', min_length=1)
    remarks: Optional[Remarks] = None


class ResponsibleParty(OscalBaseModel):
    """
    A reference to a set of persons and/or organizations that have responsibility for performing the referenced role in the context of the containing object.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    role_id: TokenDatatype = Field(..., alias='role-id', description='A reference to a role performed by a party.', title='Responsible Role')
    party_uuids: List[PartyUuid] = Field(..., alias='party-uuids', min_length=1)
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class RequiredAsset(OscalBaseModel):
    """
    Identifies an asset required to achieve remediation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this required asset elsewhere in this or other OSCAL instances. The locally defined UUID of the asset can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Required Universally Unique Identifier',
    )
    subjects: Optional[List[SubjectReference]] = Field(None, min_length=1)
    title: Optional[str] = Field(None, description='The title for this required asset.', title='Title for Required Asset')
    description: str = Field(..., description='A human-readable description of this required asset.', title='Description of Required Asset')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class RelevantEvidence(OscalBaseModel):
    """
    Links this observation to relevant evidence.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[URIReferenceDatatype] = Field(None, description='A resolvable URL reference to relevant evidence.', title='Relevant Evidence Reference')
    description: str = Field(..., description='A human-readable description of this evidence.', title='Relevant Evidence Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class Published(RootModel[DateTimeWithTimezoneDatatype]):
    root: DateTimeWithTimezoneDatatype = Field(..., description='The date and time the document was last made available.', title='Publication Timestamp')


class Protocol(OscalBaseModel):
    """
    Information about the protocol used to provide a service.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: Optional[UUIDDatatype] = Field(
        None,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this service protocol information elsewhere in this or other OSCAL instances. The locally defined UUID of the service protocol can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Service Protocol Information Universally Unique Identifier',
    )
    name: Optional[StringDatatype] = Field(None, description='The common name of the protocol, which should be the appropriate "service name" from the IANA Service Name and Transport Protocol Port Number Registry.', title='Protocol Name')
    title: Optional[str] = Field(None, description='A human readable name for the protocol (e.g., Transport Layer Security).', title='Protocol Title')
    port_ranges: Optional[List[PortRange]] = Field(None, alias='port-ranges', min_length=1)


class SystemComponent(OscalBaseModel):
    """
    A defined component that can be part of an implemented system.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this component elsewhere in this or other OSCAL instances. The locally defined UUID of the component can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Component Identifier',
    )
    type: Union[StringDatatype, SystemComponentTypeValidValues] = Field(..., description='A category describing the purpose of the component.', title='Component Type')
    title: str = Field(..., description='A human readable name for the system component.', title='Component Title')
    description: str = Field(..., description='A description of the component, including information about its function.', title='Component Description')
    purpose: Optional[str] = Field(None, description='A summary of the technological or business purpose of the component.', title='Purpose')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    status: Status = Field(..., description='Describes the operational status of the system component.', title='Status')
    responsible_roles: Optional[List[ResponsibleRole]] = Field(None, alias='responsible-roles', min_length=1)
    protocols: Optional[List[Protocol]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class Part(OscalBaseModel):
    """
    An annotated, markup-based textual element of a control's or catalog group's definition, or a child of another part.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[TokenDatatype] = Field(None, description='A unique identifier for the part.', title='Part Identifier')
    name: TokenDatatype = Field(..., description="A textual label that uniquely identifies the part's semantic type, which exists in a value space qualified by the ns.", title='Part Name')
    ns: Optional[URIDatatype] = Field(None, description="An optional namespace qualifying the part's name. This allows different organizations to associate distinct semantics with the same name.", title='Part Namespace')
    class_: Optional[TokenDatatype] = Field(None, alias='class', description="An optional textual providing a sub-type or characterization of the part's name, or a category to which the part belongs.", title='Part Class')
    title: Optional[str] = Field(None, description='An optional name given to the part, which may be used by a tool for display and navigation.', title='Part Title')
    props: Optional[List[Property]] = Field(None, min_length=1)
    prose: Optional[str] = Field(None, description='Permits multiple paragraphs, lists, tables etc.', title='Part Text')
    parts: Optional[List[Part]] = None
    links: Optional[List[Link]] = Field(None, min_length=1)


class LocalObjective(OscalBaseModel):
    """
    A local definition of a control objective for this assessment. Uses catalog syntax for control objective and assessment actions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    control_id: TokenDatatype = Field(..., alias='control-id', description='A reference to a control with a corresponding id value. When referencing an externally defined control, the Control Identifier Reference must be used in the context of the external / imported OSCAL instance (e.g., uri-reference).', title='Control Identifier Reference')
    description: Optional[str] = Field(None, description='A human-readable description of this control objective.', title='Objective Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    parts: List[Part] = Field(..., min_length=1)
    remarks: Optional[Remarks] = None


class ParameterSelection(OscalBaseModel):
    """
    Presenting a choice among alternatives.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    how_many: Optional[HowManyValidValues] = Field(None, alias='how-many', description='Describes the number of selections that must occur. Without this setting, only one value should be assumed to be permitted.', title='Parameter Cardinality')
    choice: Optional[List[str]] = Field(None, min_length=1)


class Parameter(OscalBaseModel):
    """
    Parameters provide a mechanism for the dynamic assignment of value(s) in a control.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: TokenDatatype = Field(..., description='A unique identifier for the parameter.', title='Parameter Identifier')
    class_: Optional[TokenDatatype] = Field(None, alias='class', description='A textual label that provides a characterization of the type, purpose, use or scope of the parameter.', title='Parameter Class')
    depends_on: Optional[TokenDatatype] = Field(None, alias='depends-on', description='(deprecated) Another parameter invoking this one. This construct has been deprecated and should not be used.', title='Depends on')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    label: Optional[str] = Field(None, description='A short, placeholder name for the parameter, which can be used as a substitute for a value if no value is assigned.', title='Parameter Label')
    usage: Optional[str] = Field(None, description='Describes the purpose and use of a parameter.', title='Parameter Usage Description')
    constraints: Optional[List[ParameterConstraint]] = Field(None, min_length=1)
    guidelines: Optional[List[ParameterGuideline]] = Field(None, min_length=1)
    values: Optional[List[ParameterValue]] = Field(None, min_length=1)
    select: Optional[ParameterSelection] = None
    remarks: Optional[Remarks] = None


class OriginActor(OscalBaseModel):
    """
    The actor that produces an observation, a finding, or a risk. One or more actor type can be used to specify a person that is using a tool.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: OriginActorValidValues = Field(..., description='The kind of actor.', title='Actor Type')
    actor_uuid: UUIDDatatype = Field(..., alias='actor-uuid', description='A machine-oriented identifier reference to the tool or person based on the associated type.', title='Actor Universally Unique Identifier Reference')
    role_id: Optional[TokenDatatype] = Field(None, alias='role-id', description='For a party, this can optionally be used to specify the role the actor was performing.', title='Actor Role')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)


class OnDate(OscalBaseModel):
    """
    The task is intended to occur on the specified date.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    date: DateTimeWithTimezoneDatatype = Field(..., description='The task must occur on the specified date.', title='On Date Condition')


class Timing(OscalBaseModel):
    """
    The timing under which the task is intended to occur.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    on_date: Optional[OnDate] = Field(None, alias='on-date', description='The task is intended to occur on the specified date.', title='On Date Condition')
    within_date_range: Optional[WithinDateRange] = Field(None, alias='within-date-range', description='The task is intended to occur within the specified date range.', title='On Date Range Condition')
    at_frequency: Optional[AtFrequency] = Field(None, alias='at-frequency', description='The task is intended to occur at the specified frequency.', title='Frequency Condition')


class LastModified(RootModel[DateTimeWithTimezoneDatatype]):
    root: DateTimeWithTimezoneDatatype = Field(..., description='The date and time the document was last stored for later retrieval.', title='Last Modified Timestamp')


class ImplementedComponent(OscalBaseModel):
    """
    The set of components that are implemented in a given system inventory item.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    component_uuid: UUIDDatatype = Field(..., alias='component-uuid', description='A machine-oriented identifier reference to a component that is implemented as part of an inventory item.', title='Component Universally Unique Identifier Reference')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    responsible_parties: Optional[List[ResponsibleParty]] = Field(None, alias='responsible-parties', min_length=1)
    remarks: Optional[Remarks] = None


class InventoryItem(OscalBaseModel):
    """
    A single managed inventory item within the system.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this inventory item elsewhere in this or other OSCAL instances. The locally defined UUID of the inventory item can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Inventory Item Universally Unique Identifier',
    )
    description: str = Field(..., description='A summary of the inventory item stating its purpose within the system.', title='Inventory Item Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    responsible_parties: Optional[List[ResponsibleParty]] = Field(None, alias='responsible-parties', min_length=1)
    implemented_components: Optional[List[ImplementedComponent]] = Field(None, alias='implemented-components', min_length=1)
    remarks: Optional[Remarks] = None


class IdentifiedSubject(OscalBaseModel):
    """
    Used to detail assessment subjects that were identfied by this task.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject_placeholder_uuid: UUIDDatatype = Field(..., alias='subject-placeholder-uuid', description='A machine-oriented identifier reference to a unique assessment subject placeholder defined by this task.', title='Assessment Subject Placeholder Universally Unique Identifier Reference')
    subjects: List[AssessmentSubject] = Field(..., min_length=1)


class RelatedTask(OscalBaseModel):
    """
    Identifies an individual task for which the containing object is a consequence of.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    task_uuid: UUIDDatatype = Field(..., alias='task-uuid', description='A machine-oriented identifier reference to a unique task.', title='Task Universally Unique Identifier Reference')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    responsible_parties: Optional[List[ResponsibleParty]] = Field(None, alias='responsible-parties', min_length=1)
    subjects: Optional[List[AssessmentSubject]] = Field(None, min_length=1)
    identified_subject: Optional[IdentifiedSubject] = Field(None, alias='identified-subject', description='Used to detail assessment subjects that were identfied by this task.', title='Identified Subject')
    remarks: Optional[Remarks] = None


class Origin(OscalBaseModel):
    """
    Identifies the source of the finding, such as a tool, interviewed person, or activity.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    actors: List[OriginActor] = Field(..., min_length=1)
    related_tasks: Optional[List[RelatedTask]] = Field(None, alias='related-tasks', min_length=1)


class Hash(OscalBaseModel):
    """
    A representation of a cryptographic digest generated over a resource using a specified hash algorithm.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: Union[StringDatatype, Algorithm] = Field(..., description='The digest method by which a hash is derived.', title='Hash algorithm')
    value: StringDatatype


class Rlink(OscalBaseModel):
    """
    A URL-based pointer to an external resource with an optional hash for verification and change detection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    href: URIReferenceDatatype = Field(..., description='A resolvable URL pointing to the referenced resource.', title='Hypertext Reference')
    media_type: Optional[StringDatatype] = Field(None, alias='media-type', description='A label that indicates the nature of a resource, as a data serialization or format.', title='Media Type')
    hashes: Optional[List[Hash]] = Field(None, min_length=1)


class Resource(OscalBaseModel):
    """
    A resource associated with content in the containing document instance. A resource may be directly included in the document using base64 encoding or may point to one or more equivalent internet resources.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(..., description='A unique identifier for a resource.', title='Resource Universally Unique Identifier')
    title: Optional[str] = Field(None, description='An optional name given to the resource, which may be used by a tool for display and navigation.', title='Resource Title')
    description: Optional[str] = Field(None, description='An optional short summary of the resource used to indicate the purpose of the resource.', title='Resource Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    document_ids: Optional[List[DocumentId]] = Field(None, alias='document-ids', min_length=1)
    citation: Optional[Citation] = Field(None, description='An optional citation consisting of end note text using structured markup.', title='Citation')
    rlinks: Optional[List[Rlink]] = Field(None, min_length=1)
    base64: Optional[Base64] = Field(None, description='A resource encoded using the Base64 alphabet defined by RFC 2045.', title='Base64')
    remarks: Optional[Remarks] = None


class BackMatter(OscalBaseModel):
    """
    A collection of resources that may be referenced from within the OSCAL document instance.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    resources: Optional[List[Resource]] = Field(None, min_length=1)


class Finding(OscalBaseModel):
    """
    Describes an individual finding.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this finding in this or other OSCAL instances. The locally defined UUID of the finding can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Finding Universally Unique Identifier',
    )
    title: str = Field(..., description='The title for this finding.', title='Finding Title')
    description: str = Field(..., description='A human-readable description of this finding.', title='Finding Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    origins: Optional[List[Origin]] = Field(None, min_length=1)
    target: FindingTarget
    implementation_statement_uuid: Optional[UUIDDatatype] = Field(None, alias='implementation-statement-uuid', description='A machine-oriented identifier reference to the implementation statement in the SSP to which this finding is related.', title='Implementation Statement UUID')
    related_observations: Optional[List[RelatedObservation]] = Field(None, alias='related-observations', min_length=1)
    related_risks: Optional[List[RelatedRisk]] = Field(None, alias='related-risks', min_length=1)
    remarks: Optional[Remarks] = None


class Characterization(OscalBaseModel):
    """
    A collection of descriptive data about the containing object from a specific origin.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    origin: Origin
    facets: List[Facet] = Field(..., min_length=1)


class AssociatedActivity(OscalBaseModel):
    """
    Identifies an individual activity to be performed as part of a task.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    activity_uuid: UUIDDatatype = Field(..., alias='activity-uuid', description='A machine-oriented identifier reference to an activity defined in the list of activities.', title='Activity Universally Unique Identifier Reference')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    responsible_roles: Optional[List[ResponsibleRole]] = Field(None, alias='responsible-roles', min_length=1)
    subjects: List[AssessmentSubject] = Field(..., min_length=1)
    remarks: Optional[Remarks] = None


class Task(OscalBaseModel):
    """
    Represents a scheduled event or milestone, which may be associated with a series of assessment actions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this task elsewhere in this or other OSCAL instances. The locally defined UUID of the task can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Task Universally Unique Identifier',
    )
    type: Union[TokenDatatype, TaskValidValues] = Field(..., description='The type of task.', title='Task Type')
    title: str = Field(..., description='The title for this task.', title='Task Title')
    description: Optional[str] = Field(None, description='A human-readable description of this task.', title='Task Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    timing: Optional[Timing] = Field(None, description='The timing under which the task is intended to occur.', title='Event Timing')
    dependencies: Optional[List[Dependency]] = Field(None, min_length=1)
    tasks: Optional[List[Task]] = None
    associated_activities: Optional[List[AssociatedActivity]] = Field(None, alias='associated-activities', min_length=1)
    subjects: Optional[List[AssessmentSubject]] = Field(None, min_length=1)
    responsible_roles: Optional[List[ResponsibleRole]] = Field(None, alias='responsible-roles', min_length=1)
    remarks: Optional[Remarks] = None


class Response(OscalBaseModel):
    """
    Describes either recommended or an actual plan for addressing the risk.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this remediation elsewhere in this or other OSCAL instances. The locally defined UUID of the risk response can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Remediation Universally Unique Identifier',
    )
    lifecycle: Union[TokenDatatype, Lifecycle] = Field(..., description='Identifies whether this is a recommendation, such as from an assessor or tool, or an actual plan accepted by the system owner.', title='Remediation Intent')
    title: str = Field(..., description='The title for this response activity.', title='Response Title')
    description: str = Field(..., description='A human-readable description of this response plan.', title='Response Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    origins: Optional[List[Origin]] = Field(None, min_length=1)
    required_assets: Optional[List[RequiredAsset]] = Field(None, alias='required-assets', min_length=1)
    tasks: Optional[List[Task]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class Address(OscalBaseModel):
    """
    A postal address for the location.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Optional[Union[TokenDatatype, AddressTypeValidValues]] = Field(None, description='Indicates the type of address.', title='Address Type')
    addr_lines: Optional[List[AddrLine]] = Field(None, alias='addr-lines', min_length=1)
    city: Optional[StringDatatype] = Field(None, description='City, town or geographical region for the mailing address.', title='City')
    state: Optional[StringDatatype] = Field(None, description='State, province or analogous geographical region for a mailing address.', title='State')
    postal_code: Optional[StringDatatype] = Field(None, alias='postal-code', description='Postal or ZIP code for mailing address.', title='Postal Code')
    country: Optional[StringDatatype] = Field(None, description='The ISO 3166-1 alpha-2 country code for the mailing address.', title='Country Code')


class Party(OscalBaseModel):
    """
    An organization or person, which may be associated with roles or other concepts within the current or linked OSCAL document.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(..., description='A unique identifier for the party.', title='Party Universally Unique Identifier')
    type: PartyTypeValidValues = Field(..., description='A category describing the kind of party the object describes.', title='Party Type')
    name: Optional[StringDatatype] = Field(None, description='The full name of the party. This is typically the legal name associated with the party.', title='Party Name')
    short_name: Optional[StringDatatype] = Field(None, alias='short-name', description='A short common name, abbreviation, or acronym for the party.', title='Party Short Name')
    external_ids: Optional[List[ExternalId]] = Field(None, alias='external-ids', min_length=1)
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    email_addresses: Optional[List[EmailAddress]] = Field(None, alias='email-addresses', min_length=1)
    telephone_numbers: Optional[List[TelephoneNumber]] = Field(None, alias='telephone-numbers', min_length=1)
    addresses: Optional[List[Address]] = Field(None, min_length=1)
    location_uuids: Optional[List[LocationUuid]] = Field(None, alias='location-uuids', min_length=1)
    member_of_organizations: Optional[List[UUIDDatatype]] = Field(None, alias='member-of-organizations', min_length=1)
    remarks: Optional[Remarks] = None


class Action(OscalBaseModel):
    """
    An action applied by a role within a given party to the content.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(..., description='A unique identifier that can be used to reference this defined action elsewhere in an OSCAL document. A UUID should be consistently used for a given location across revisions of the document.', title='Action Universally Unique Identifier')
    date: Optional[DateTimeWithTimezoneDatatype] = Field(None, description='The date and time when the action occurred.', title='Action Occurrence Date')
    type: TokenDatatype = Field(..., description='The type of action documented by the assembly, such as an approval.', title='Action Type')
    system: URIDatatype = Field(..., description='Specifies the action type system used.', title='Action Type System')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    responsible_parties: Optional[List[ResponsibleParty]] = Field(None, alias='responsible-parties', min_length=1)
    remarks: Optional[Remarks] = None


class UsesComponent(OscalBaseModel):
    """
    The set of components that are used by the assessment platform.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    component_uuid: UUIDDatatype = Field(..., alias='component-uuid', description='A machine-oriented identifier reference to a component that is implemented as part of an inventory item.', title='Component Universally Unique Identifier Reference')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    responsible_parties: Optional[List[ResponsibleParty]] = Field(None, alias='responsible-parties', min_length=1)
    remarks: Optional[Remarks] = None


class AssessmentPlatform(OscalBaseModel):
    """
    Used to represent the toolset used to perform aspects of the assessment.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this assessment platform elsewhere in this or other OSCAL instances. The locally defined UUID of the assessment platform can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Assessment Platform Universally Unique Identifier',
    )
    title: Optional[str] = Field(None, description='The title or name for the assessment platform.', title='Assessment Platform Title')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    uses_components: Optional[List[UsesComponent]] = Field(None, alias='uses-components', min_length=1)
    remarks: Optional[Remarks] = None


class AssessmentAssets(OscalBaseModel):
    """
    Identifies the assets used to perform this assessment, such as the assessment team, scanning tools, and assumptions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    components: Optional[List[SystemComponent]] = Field(None, min_length=1)
    assessment_platforms: List[AssessmentPlatform] = Field(..., alias='assessment-platforms', min_length=1)


class Location(OscalBaseModel):
    """
    A physical point of presence, which may be associated with people, organizations, or other concepts within the current or linked OSCAL document.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(..., description='A unique ID for the location, for reference.', title='Location Universally Unique Identifier')
    title: Optional[str] = Field(None, description='A name given to the location, which may be used by a tool for display and navigation.', title='Location Title')
    address: Optional[Address] = None
    email_addresses: Optional[List[EmailAddress]] = Field(None, alias='email-addresses', min_length=1)
    telephone_numbers: Optional[List[TelephoneNumber]] = Field(None, alias='telephone-numbers', min_length=1)
    urls: Optional[List[URIDatatype]] = Field(None, min_length=1)
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class Step(OscalBaseModel):
    """
    Identifies an individual step in a series of steps related to an activity, such as an assessment test or examination procedure.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this step elsewhere in this or other OSCAL instances. The locally defined UUID of the step (in a series of steps) can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Step Universally Unique Identifier',
    )
    title: Optional[str] = Field(None, description='The title for this step.', title='Step Title')
    description: str = Field(..., description='A human-readable description of this step.', title='Step Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    reviewed_controls: Optional[ReviewedControls] = Field(None, alias='reviewed-controls')
    responsible_roles: Optional[List[ResponsibleRole]] = Field(None, alias='responsible-roles', min_length=1)
    remarks: Optional[Remarks] = None


class Activity(OscalBaseModel):
    """
    Identifies an assessment or related process that can be performed. In the assessment plan, this is an intended activity which may be associated with an assessment task. In the assessment results, this an activity that was actually performed as part of an assessment.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this assessment activity elsewhere in this or other OSCAL instances. The locally defined UUID of the activity can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Assessment Activity Universally Unique Identifier',
    )
    title: Optional[str] = Field(None, description='The title for this included activity.', title='Included Activity Title')
    description: str = Field(..., description='A human-readable description of this included activity.', title='Included Activity Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    steps: Optional[List[Step]] = Field(None, min_length=1)
    related_controls: Optional[ReviewedControls] = Field(None, alias='related-controls')
    responsible_roles: Optional[List[ResponsibleRole]] = Field(None, alias='responsible-roles', min_length=1)
    remarks: Optional[Remarks] = None


class Revision(OscalBaseModel):
    """
    An entry in a sequential list of revisions to the containing document, expected to be in reverse chronological order (i.e. latest first).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    title: Optional[str] = Field(None, description='A name given to the document revision, which may be used by a tool for display and navigation.', title='Document Title')
    published: Optional[Published] = None
    last_modified: Optional[LastModified] = Field(None, alias='last-modified')
    version: Version
    oscal_version: Optional[OscalVersion] = Field(None, alias='oscal-version')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class Metadata(OscalBaseModel):
    """
    Provides information about the containing document, and defines concepts that are shared across the document.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., description='A name given to the document, which may be used by a tool for display and navigation.', title='Document Title')
    published: Optional[Published] = None
    last_modified: LastModified = Field(..., alias='last-modified')
    version: Version
    oscal_version: OscalVersion = Field(..., alias='oscal-version')
    revisions: Optional[List[Revision]] = Field(None, min_length=1)
    document_ids: Optional[List[DocumentId]] = Field(None, alias='document-ids', min_length=1)
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    roles: Optional[List[Role]] = Field(None, min_length=1)
    locations: Optional[List[Location]] = Field(None, min_length=1)
    parties: Optional[List[Party]] = Field(None, min_length=1)
    responsible_parties: Optional[List[ResponsibleParty]] = Field(None, alias='responsible-parties', min_length=1)
    actions: Optional[List[Action]] = Field(None, min_length=1)
    remarks: Optional[Remarks] = None


class Observation(OscalBaseModel):
    """
    Describes an individual observation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this observation elsewhere in this or other OSCAL instances. The locally defined UUID of the observation can be used to reference the data item locally or globally (e.g., in an imorted OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Observation Universally Unique Identifier',
    )
    title: Optional[str] = Field(None, description='The title for this observation.', title='Observation Title')
    description: str = Field(..., description='A human-readable description of this assessment observation.', title='Observation Description')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    methods: List[Union[StringDatatype, Methods]] = Field(..., min_length=1)
    types: Optional[List[Union[TokenDatatype, ObservationTypeValidValues]]] = Field(None, min_length=1)
    origins: Optional[List[Origin]] = Field(None, min_length=1)
    subjects: Optional[List[SubjectReference]] = Field(None, min_length=1)
    relevant_evidence: Optional[List[RelevantEvidence]] = Field(None, alias='relevant-evidence', min_length=1)
    collected: DateTimeWithTimezoneDatatype = Field(..., description='Date/time stamp identifying when the finding information was collected.', title='Collected Field')
    expires: Optional[DateTimeWithTimezoneDatatype] = Field(None, description='Date/time identifying when the finding information is out-of-date and no longer valid. Typically used with continuous assessment scenarios.', title='Expires Field')
    remarks: Optional[Remarks] = None


class RelatedResponse(OscalBaseModel):
    """
    Identifies an individual risk response that this log entry is for.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    response_uuid: UUIDDatatype = Field(..., alias='response-uuid', description='A machine-oriented identifier reference to a unique risk response.', title='Response Universally Unique Identifier Reference')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    related_tasks: Optional[List[RelatedTask]] = Field(None, alias='related-tasks', min_length=1)
    remarks: Optional[Remarks] = None


class Entry(OscalBaseModel):
    """
    Identifies an individual risk response that occurred as part of managing an identified risk.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this risk log entry elsewhere in this or other OSCAL instances. The locally defined UUID of the risk log entry can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Risk Log Entry Universally Unique Identifier',
    )
    title: Optional[str] = Field(None, description='The title for this risk log entry.', title='Title')
    description: Optional[str] = Field(None, description='A human-readable description of what was done regarding the risk.', title='Risk Task Description')
    start: DateTimeWithTimezoneDatatype = Field(..., description='Identifies the start date and time of the event.', title='Start')
    end: Optional[DateTimeWithTimezoneDatatype] = Field(None, description='Identifies the end date and time of the event. If the event is a point in time, the start and end will be the same date and time.', title='End')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    logged_by: Optional[List[LoggedBy]] = Field(None, alias='logged-by', min_length=1)
    status_change: Optional[RiskStatus] = Field(None, alias='status-change')
    related_responses: Optional[List[RelatedResponse]] = Field(None, alias='related-responses', min_length=1)
    remarks: Optional[Remarks] = None


class RiskLog(OscalBaseModel):
    """
    A log of all risk-related tasks taken.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    entries: List[Entry] = Field(..., min_length=1)


class Risk(OscalBaseModel):
    """
    An identified risk.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: UUIDDatatype = Field(
        ...,
        description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this risk elsewhere in this or other OSCAL instances. The locally defined UUID of the risk can be used to reference the data item locally or globally (e.g., in an imported OSCAL instance). This UUID should be assigned per-subject, which means it should be consistently used to identify the same subject across revisions of the document.',
        title='Risk Universally Unique Identifier',
    )
    title: str = Field(..., description='The title for this risk.', title='Risk Title')
    description: str = Field(..., description='A human-readable summary of the identified risk, to include a statement of how the risk impacts the system.', title='Risk Description')
    statement: str = Field(..., description='An summary of impact for how the risk affects the system.', title='Risk Statement')
    props: Optional[List[Property]] = Field(None, min_length=1)
    links: Optional[List[Link]] = Field(None, min_length=1)
    status: RiskStatus
    origins: Optional[List[Origin]] = Field(None, min_length=1)
    threat_ids: Optional[List[ThreatId]] = Field(None, alias='threat-ids', min_length=1)
    characterizations: Optional[List[Characterization]] = Field(None, min_length=1)
    mitigating_factors: Optional[List[MitigatingFactor]] = Field(None, alias='mitigating-factors', min_length=1)
    deadline: Optional[DateTimeWithTimezoneDatatype] = Field(None, description='The date/time by which the risk must be resolved.', title='Risk Resolution Deadline')
    remediations: Optional[List[Response]] = Field(None, min_length=1)
    risk_log: Optional[RiskLog] = Field(None, alias='risk-log', description='A log of all risk-related tasks taken.', title='Risk Log')
    related_observations: Optional[List[RelatedObservation]] = Field(None, alias='related-observations', min_length=1)


