# -*- mode:python; coding:utf-8 -*-
# Copyright (c) 2020 IBM Corp. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
#
####### DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT ######
#                                                                        #
#        This file is automatically generated by gen_oscal.py            #
#                                                                        #
####### DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT ######
#
#
from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, AwareDatetime, ConfigDict, EmailStr, Field, RootModel, conint, constr, field_validator

from trestle.core.base_model import OscalBaseModel
from trestle.oscal import OSCAL_VERSION_REGEX, OSCAL_VERSION
import trestle.oscal.common as common
from trestle.oscal.common import StringDatatype
from trestle.oscal.common import URIReferenceDatatype


class DefinedComponentTypeValidValues(Enum):
    interconnection = 'interconnection'
    software = 'software'
    hardware = 'hardware'
    service = 'service'
    policy = 'policy'
    physical = 'physical'
    process_procedure = 'process-procedure'
    plan = 'plan'
    guidance = 'guidance'
    standard = 'standard'
    validation = 'validation'


class ImportComponentDefinition(OscalBaseModel):
    """
    Loads a component definition from another resource.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    href: str = Field(..., description='A link to a resource that defines a set of components and/or capabilities to import into this collection.', title='Hyperlink Reference')
    remarks: str | None = None


class IncorporatesComponent(OscalBaseModel):
    """
    The collection of components comprising this capability.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    component_uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., alias='component-uuid', description='A machine-oriented identifier reference to a component.', title='Component Reference')
    description: str = Field(..., description='A description of the component, including information about its function.', title='Component Description')


class Statement(OscalBaseModel):
    """
    Identifies which statements within a control are addressed.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    statement_id: constr(pattern=r'^[_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD][_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\-\.0-9\u00B7\u0300-\u036F\u203F-\u2040]*$') = Field(..., alias='statement-id', description='A human-oriented identifier reference to a control statement.', title='Control Statement Reference')
    uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., description='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this control statement elsewhere in this or other OSCAL instances. The UUID of the control statement in the source OSCAL instance is sufficient to reference the data item locally or globally (e.g., in an imported OSCAL instance).', title='Control Statement Reference Universally Unique Identifier')
    description: str = Field(..., description='A summary of how the containing control statement is implemented by the component or capability.', title='Statement Implementation Description')
    props: list[common.Property] | None = Field(None, min_length=1)
    links: list[common.Link] | None = Field(None, min_length=1)
    responsible_roles: list[common.ResponsibleRole] | None = Field(None, alias='responsible-roles', min_length=1)
    remarks: str | None = None


class ImplementedRequirement(OscalBaseModel):
    """
    Describes how the containing component or capability implements an individual control.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., description='Provides a globally unique means to identify a given control implementation by a component.', title='Control Implementation Identifier')
    control_id: constr(pattern=r'^[_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD][_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\-\.0-9\u00B7\u0300-\u036F\u203F-\u2040]*$') = Field(..., alias='control-id', description='A reference to a control with a corresponding id value. When referencing an externally defined control, the Control Identifier Reference must be used in the context of the external / imported OSCAL instance (e.g., uri-reference).', title='Control Identifier Reference')
    description: str = Field(..., description='A suggestion from the supplier (e.g., component vendor or author) for how the specified control may be implemented if the containing component or capability is instantiated in a system security plan.', title='Control Implementation Description')
    props: list[common.Property] | None = Field(None, min_length=1)
    links: list[common.Link] | None = Field(None, min_length=1)
    set_parameters: list[common.SetParameter] | None = Field(None, alias='set-parameters', min_length=1)
    responsible_roles: list[common.ResponsibleRole] | None = Field(None, alias='responsible-roles', min_length=1)
    statements: list[Statement] | None = Field(None, min_length=1)
    remarks: str | None = None


class ControlImplementation(OscalBaseModel):
    """
    Defines how the component or capability supports a set of controls.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., description='Provides a means to identify a set of control implementations that are supported by a given component or capability.', title='Control Implementation Set Identifier')
    source: str = Field(..., description='A reference to an OSCAL catalog or profile providing the referenced control or subcontrol definition.', title='Source Resource Reference')
    description: str = Field(..., description='A description of how the specified set of controls are implemented for the containing component or capability.', title='Control Implementation Description')
    props: list[common.Property] | None = Field(None, min_length=1)
    links: list[common.Link] | None = Field(None, min_length=1)
    set_parameters: list[common.SetParameter] | None = Field(None, alias='set-parameters', min_length=1)
    implemented_requirements: list[ImplementedRequirement] = Field(..., alias='implemented-requirements', min_length=1)


class DefinedComponent(OscalBaseModel):
    """
    A defined component that can be part of an implemented system.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., description='Provides a globally unique means to identify a given component.', title='Component Identifier')
    type: StringDatatype | DefinedComponentTypeValidValues = Field(..., description='A category describing the purpose of the component.', title='Component Type')
    title: constr(pattern=r'^[^\n]+$') = Field(..., description='A human readable name for the component.', title='Component Title')
    description: str = Field(..., description='A description of the component, including information about its function.', title='Component Description')
    purpose: constr(pattern=r'^[^\n]+$') | None = Field(None, description='A summary of the technological or business purpose of the component.', title='Purpose')
    props: list[common.Property] | None = Field(None, min_length=1)
    links: list[common.Link] | None = Field(None, min_length=1)
    responsible_roles: list[common.ResponsibleRole] | None = Field(None, alias='responsible-roles', min_length=1)
    protocols: list[common.Protocol] | None = Field(None, min_length=1)
    control_implementations: list[ControlImplementation] | None = Field(None, alias='control-implementations', min_length=1)
    remarks: str | None = None


class Capability(OscalBaseModel):
    """
    A grouping of other components and/or capabilities.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., description='Provides a globally unique means to identify a given capability.', title='Capability Identifier')
    name: constr(pattern=r'^\S(.*\S)?$') = Field(..., description="The capability's human-readable name.", title='Capability Name')
    description: str = Field(..., description='A summary of the capability.', title='Capability Description')
    props: list[common.Property] | None = Field(None, min_length=1)
    links: list[common.Link] | None = Field(None, min_length=1)
    incorporates_components: list[IncorporatesComponent] | None = Field(None, alias='incorporates-components', min_length=1)
    control_implementations: list[ControlImplementation] | None = Field(None, alias='control-implementations', min_length=1)
    remarks: str | None = None


class ComponentDefinition(OscalBaseModel):
    """
    A collection of component descriptions, which may optionally be grouped by capability.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: constr(pattern=r'^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[45][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$') = Field(..., description='Provides a globally unique means to identify a given component definition instance.', title='Component Definition Universally Unique Identifier')
    metadata: common.Metadata
    import_component_definitions: list[ImportComponentDefinition] | None = Field(None, alias='import-component-definitions', min_length=1)
    components: list[DefinedComponent] | None = Field(None, min_length=1)
    capabilities: list[Capability] | None = Field(None, min_length=1)
    back_matter: common.BackMatter | None = Field(None, alias='back-matter')


# Backward compatibility alias for OSCAL 1.2.0
# SetParameter is now only in common module
SetParameter = common.SetParameter


class Model(OscalBaseModel):
    component_definition: ComponentDefinition = Field(..., alias='component-definition')
