name: Test workflows with act

on:
  pull_request:
    types: [labeled, synchronize, opened]
    paths:
      - '.github/**'

permissions: read-all

jobs:
  act-dry-run:
    if: contains(github.event.pull_request.labels.*.name, 'github_actions')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true

    - name: Install act
      run: |
        curl -fsSL https://raw.githubusercontent.com/nektos/act/36add66f6520c77c15dfce4715ba6c689d427981/install.sh | sudo bash -s -- -b /usr/local/bin v0.2.87
        mkdir -p ~/.config/act
        printf -- '-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest\n' > ~/.config/act/actrc

    - name: Dry-run actionlint workflow
      run: |
        act -n -W .github/workflows/actionlint.yml --container-architecture linux/amd64

    - name: Dry-run PR test pipeline
      run: |
        act -n -W .github/workflows/python-test.yml --container-architecture linux/amd64

    - name: Dry-run deploy pipeline
      run: |
        act -n -W .github/workflows/python-push.yml --container-architecture linux/amd64

    - name: Dry-run conventional PR pipeline
      run: |
        act -n -W .github/workflows/conventional-pr.yml --container-architecture linux/amd64
